.vscode/settings.json, README.md, package.json, src/commands/README.md, src/commands/index.ts, src/extension.ts, src/mdb.ts, src/test/runTest.ts, src/test/suite/extension.test.ts, src/test/suite/index.ts, src/test/suite/stubs.ts, tslint.json
https://jira.mongodb.org/browse/VSCODE-16
This PR adds the command handling for the following commands:
- `mdb.connect`
- `mdb.addConnection`
- `mdb.connectWithURI`
- `mdb.addConnectionWithURI`
- `mdb.removeConnection`
- `mdb.launchMongoShell`
They don't yet talk to mongo, that's coming in [VSCODE-12](https://jira.mongodb.org/browse/VSCODE-12). We're just doing some basic handling here and dialogue windows.
I also cleaned up the commands listed in the [commands README](https://github.com/mongodb-js/vscode/blob/VSCODE-16/initial-command-definition/src/commands/README.md) so we can use that as more of a solid resource for which commands we'll handle going forward. I opted not to add stubs for not yet implemented commands just yet to keep things a little more readable.
Adding/removing a …
=> VSCODE-16 Add initial extension commands

package.json, src/connectionController.ts, src/mdbExtensionController.ts
* Env variable hack to launch a shell that is connected
to the same cluster the extension is already connected to.
* Configuration to select what shell to use (mongo or mongosh)
=> Launch shell connected to active connection

package.json, src/connectionController.ts
As the extension is using Compass' connection model and data service, the client metadata was set to `MongoDB Compass` by default.
With this change we set it with name + version from `package.json`.
Also, changed the name in package.json to `mongodb-vscode` as it makes it more npm-searchable.
=> VSCODE-35: Set correct client metadata

package-lock.json, src/scripts/get-snippets.ts, src/snippets/stage-autocompleter.json
Some agg stages' comments contain `$` symbol that is being interpreted as variable name, but the variable is not known. The solution is to escape this symbol before building the stage body.
=> VSCODE-31: escape dollars in comments

azure-pipelines.yml, package.json, src/test/runTest.ts
- I have noticed that `npm run test` triggers the test running process two times instead of one. The first run includes zero tests and the second run actually does the job.
The reason is that we use `vscode-test` runner but in package.json we try to run this runner using a mocha runner :) `mocha ./out/test/runTest.js`
I have replaced it with `node ./out/test/runTest.js` and it solved the issue.
- Also, I removed `npm run compile` script from the `azure-pipelines.yml` because we already have this script in `pretest` script in package.json.
=> test: improve tests running

package.json, src/connectionController.ts, src/explorer/mdbConnectionsTreeItem.ts, src/extension.ts, src/mdbExtensionController.ts, src/storage/index.ts, src/storage/storageController.ts, src/test/runTest.ts, src/test/suite/connectionController.test.ts, src/test/suite/explorer/explorerController.test.ts, src/test/suite/extension.test.ts, src/test/suite/storage/storageController.test.ts, src/test/suite/stubs.ts
https://jira.mongodb.org/browse/VSCODE-34
This PR makes it so that after a new connection is added, it can be saved into either the vscode workspace, globally in vscode, or just kept on the current session. There's a setting that can disable the prompt that asks for where to save the connection in settings. There's an additional setting which dictates when the prompt is disabled, where new connections should be saved (`Global`, `Workspace`, or `Session Only`).
Currently we're storing the entire connection's driverUrl in storage. In the future we'll want to not store the password (or maybe give the option to store it). 
Another thing we could do is expose these connections as settings in the extension settings (an array or object of connections that the user can even add to or configure …
=> VSCODE-34: Save connection models

package-lock.json, package.json, src/editors/collectionDocumentsProvider.ts, src/editors/editorsController.ts, src/editors/index.ts, src/explorer/collectionTreeItem.ts, src/explorer/index.ts, src/mdbExtensionController.ts, src/test/suite/connectionController.test.ts, src/test/suite/editors/collectionDocumentsProvider.test.ts, src/test/suite/extension.test.ts, src/test/suite/mdbExtensionController.test.ts
https://jira.mongodb.org/browse/VSCODE-34
This PR adds the right click option `View Documents` to collections in the tree view. It currently shows the first `10` documents resulting from a `find` operation on the collection in a `read-only` `.json` file. In future work we're looking into code lenses to provide an option to show more documents. That work is in here: https://jira.mongodb.org/browse/VSCODE-36 I think once I add something with code lenses I'll also add in a status bar item for while we're performing the request to find the documents.
If there's an error, like internet is disconnected, an error message is displayed in the bottom right and a document like this is opened:
=> VSCODE-28: View collection in editor

src/editors/collectionDocumentsProvider.ts, src/editors/editorsController.ts, src/explorer/connectionTreeItem.ts, src/explorer/databaseTreeItem.ts, src/mdbExtensionController.ts, src/test/suite/connectionController.test.ts, src/test/suite/editors/collectionDocumentsProvider.test.ts, src/test/suite/explorer/explorerController.test.ts, src/test/suite/mdbExtensionController.test.ts, src/views/statusView.ts
https://jira.mongodb.org/browse/VSCODE-53
This PR adds showing a status bar item message when we're fetching collection documents (view documents and `show more` code lens) and when we're creating a collection (create database and create collection in the tree view). Easy way to test is to disable your internet when you run one of the commands. Hopefully this will feel like some decent feedback that the operation is running when things are taking some time.
I added context to the status view parameters so when the extension is disposed it cleans up a bit better. Going to read up on how vscode prefers disposal. ah just saw https://code.visualstudio.com/api/references/icons-in-labels might incorporate...
=> VSCODE-43: Show status bar item while fetching documents & creating collections

images/mongodb-original.svg, images/mongodb.svg, package.json, src/connectionController.ts, src/editors/collectionDocumentsCodeLensProvider.ts, src/editors/collectionDocumentsOperationsStore.ts, src/editors/collectionDocumentsProvider.ts, src/editors/editorsController.ts, src/explorer/collectionTreeItem.ts, src/explorer/connectionTreeItem.ts, src/explorer/databaseTreeItem.ts, src/explorer/documentTreeItem.ts, src/explorer/explorerController.ts, src/explorer/explorerTreeController.ts, src/extension.ts, src/mdbExtensionController.ts, src/test/suite/connectionController.test.ts, src/test/suite/editors/editorsController.test.ts, src/test/suite/explorer/databaseTreeItem.test.ts, src/test/suite/explorer/explorerController.test.ts, src/test/suite/index.ts, src/test/suite/mdbExtensionController.test.ts
https://jira.mongodb.org/browse/VSCODE-43
This PR adds the ability to `Drop Database` on a Database tree item, `Drop Collection` on a Collection tree item, and adds `Connect` and `Disconnect` to Connection tree items. Connection tree items now have different actions based on if they are connected or not.
Dropping databases and collections both have text input prompts that require the user to type in the name of the database or collection they are trying to drop.
I also lumped into this pr a bit of cleaning up on the error messages, previously we were letting vscode create error messages when commands failed, now we display them ourselves so we can remove a bit of the extra text vscode would add into the messages. Sorry for the large diff.
I added tests as end to end command handling …
=> VSCODE-52: Add connect disconnect and drop database collection explorer actions

package.json, src/explorer/collectionTreeItem.ts, src/explorer/connectionTreeItem.ts, src/explorer/databaseTreeItem.ts, src/explorer/documentListTreeItem.ts, src/explorer/fieldTreeItem.ts, src/explorer/schemaTreeItem.ts, src/mdbExtensionController.ts, src/test/suite/explorer/databaseTreeItem.test.ts, src/test/suite/explorer/fieldTreeItems.test.ts, src/test/suite/explorer/schemaTreeItem.test.ts, src/test/suite/extension.test.ts, src/test/suite/mdbExtensionController.test.ts
https://jira.mongodb.org/browse/VSCODE-59
This PR adds caching to the state of the tree view for schema. So that nested elements' collapsed states are preserved when a top level tree item is collapsed & expanded.
This PR also adds groups to the tree view to make the actions a bit more navigable and user friendly. And we have a refresh action on schema now, which reloads the schema and reset dropdown states. Ya'll think we could improve these groupings a bit? Open to suggestions.
On refresh we fetch all of the fields if the user already clicked the `show more fields` button.
**Screenshots**
___
*Caching of tree schema*
*Refresh action on schema*
*Groups in tree view actions (those lines that separate the actions are the groups)*
=> VSCODE-59: Add schema actions and cache

package-lock.json, package.json, src/connectionController.ts, src/editors/activeConnectionCodeLensProvider.ts, src/editors/playgroundController.ts, src/mdbExtensionController.ts, src/templates/playgroundTemplate.ts, src/test/suite/editors/activeDBCodeLensProvider.test.ts, src/test/suite/editors/playgroundController.test.ts, src/test/suite/mdbExtensionController.test.ts
1) Use a new version of `mongosh` with https://github.com/mongodb-js/mongosh/pull/64 merged that fixes missing db interaction commands in browser runtime (eg. `use('db')`).
2) Create a new runtime instance for each run of the playground. It will allow to repeatedly run the same commands and avoid errors such as `Unable to run playground: Identifier ‘s’ has already been declared`.
Example from @mmarcon:
```
const s = 3, l = 1;
db.users.find().skip(s).limit(l);
```
_"When I run this the first time, this works well. But then if I re-run it, I get “Unable to run playground: Identifier ‘s’ has already been declared” which in the REPL makes sense but in the playground case I’d expect that every run starts with a clean context."_
3) Display active connection instead of active db. When switching …
=> VSCODE-72: create a new runtime instance for each evaluation

README.md, package.json, src/editors/playgroundController.ts, src/test/suite/editors/playgroundController.test.ts
Put running a playground behind a prompt to avoid users accidentally messing up their data or doing unintended queries.
- Before running commands in a playground show the `Are you sure you want to run this playground against [CONNECTION_NAME]?` confirmation message.
- Add a setting that can be turned off in case people would like to live on the wild side.
=> VSCODE-67: add a confirmation when running a playground

languages/mongodb-language-configuration.json, package.json
Adds the JS static language config for now so playground editors get some basic JS bracket matching/folding/etc.
https://code.visualstudio.com/api/language-extensions/language-configuration-guide
> The [`contributes.languages`](/api/references/contribution-points#contributes.languages) Contribution Point allows you to define a language configuration that controls the following Declarative Language Features:
>
> - Comment toggling
> - Brackets definition
> - Autoclosing
> - Autosurrounding
> - Folding
> - Word pattern
> - Indentation Rules
=> feat(language): VSCODE-24: Add mongodb language configuration

.vscode/launch.json, .vscode/settings.json, README.md, package-lock.json, package.json, src/language/README.md, src/language/index.ts, src/language/langserver-diagram.svg, src/language/languageServerController.ts, src/language/server.ts, src/test/fixture/.vscode/settings.json, src/test/fixture/README.md, src/test/fixture/diagnostics.mongodb, src/test/fixture/test.mongodb, src/test/suite/language/completion.test.ts, src/test/suite/language/diagnostics.test.ts, src/test/suite/language/helper.ts
This PR provides the initial setup for MongoDB Language Server; primarily, it is documentation, dependencies and test fixture setup we'll add user-facing features on top of in the future. I also added a static mongodb language configuration in ./language for the editor.
A test fixture workspace has been added under `src/test/fixture`.
=> feat(language): VSCODE-24: Language server setup

package.json, src/connectionController.ts, src/mdbExtensionController.ts, src/test/suite/extension.test.ts
The previous implementation was always returning null.
I realized the shell was always connected to localhost and I noticed the code was looking for the connecting connection instead of the active one.
Additionally, added error message when attempting to launch a shell without an active connection.
=> Retrieve the connection string from the right place

.vscode/launch.json, package.json, scripts/generate-keyfile.ts, src/editors/playgroundController.ts, src/language/languageServerController.ts, src/language/server.ts, src/mdbExtensionController.ts, src/test/suite/editors/playgroundController.test.ts, src/test/suite/stubs.ts, src/test/suite/views/connectFormView.test.ts
- In this PR I added instantiation of Language Server to the mdbExtensionController and moved playground execution to this Language Server.
- The playground makes a call to the Language Server Client and sends two parameters: code that needs to be evaluated and driverUrl.
- The Language Server Client sends a request with these values to the Language Server Server.
- Looks like we can't use DataService in the Language Server Server. Probably because it extends from EventEmitter. But we can use CliServiceProvider from '@mongosh/service-provider-server' instead. It accepts 2 params driverUrl and driverOptions. It provides similar methods as DataService does: https://github.com/mongodb-js/mongosh/blob/master/packages/service-provider-server/src/cli-service-provider.ts. Please let me know if …
=> VSCODE-79: move playground to the language server

src/connectionController.ts, src/test/suite/connectionController.test.ts
`appname` was being set only when connecting to a new connection but not when connecting to one that was already added. This fixes it.
=> Fix: missing appname when connecting with connectionId

package.json, src/connectionController.ts, src/explorer/explorerController.ts, src/explorer/explorerTreeController.ts, src/mdbExtensionController.ts, src/test/suite/connectionController.test.ts, src/test/suite/explorer/explorerController.test.ts, src/test/suite/mdbExtensionController.test.ts
https://jira.mongodb.org/browse/VSCODE-85
This PR adds a button to the tree view for when the user has not yet added a connection.  This should improve the experience for users who have just installed the extension.
Note: If the user adds a connection and removes it, the button does not show up. If they refresh their vscode though, and there are no connections, it will show up. When they're first loading the extension and their connections have not yet loaded, the message also shows up - which might be enough of a reason not to use this button format. From what I've read it looks like there's no way for us to specify that our extension is being activated... https://github.com/microsoft/vscode/issues/59645 This will be less of an issue once we're webpacking and load times are hopefully …
=> VSCODE-85: Add default button to tree view

src/test/suite/views/webviewController.test.ts, src/views/webview-app/components/connect-form/connection-form.tsx, src/views/webview-app/extension-app-message-constants.ts, src/views/webview-app/externals.ts, src/views/webview-app/store/actions.ts, src/views/webview-app/store/store.ts, src/views/webviewController.ts
https://jira.mongodb.org/browse/VSCODE-73
Adds a button to the connect form that opens the connection string input.
=> VSCODE-73: Add connect with connection string to connect form

package.json, src/editors/playgroundController.ts, src/language/languageServerController.ts, src/language/mongoDBService.ts, src/test/helper/playgroundHelper.ts, src/test/suite/language/mongoDBService.test.ts
When adding webpack to the project, we started using bundles for the language server and language server worker. This PR updates an older file naming to use the bundled language server worker.
We also now run clean and webpack before watching for updates in files to be sure our extension can be developed properly.
I'm working on a test for this now to make sure it can't happen in future, I'll pass the extension path in a less hacky way then as well. That PR will be coming soon, this fix is just to unblock.
=> (fix): Use correct worker file name and clean and webpack before watching

package.json, src/commands/README.md, src/language/languageServerController.ts, src/language/mongoDBService.ts, src/language/playgroundRunParametersType.ts, src/language/server.ts, src/language/serverCommands.ts, src/mdbExtensionController.ts, src/test/suite/extension.test.ts, src/test/suite/language/languageServerController.test.ts, src/test/suite/language/mongoDBService.test.ts, src/test/suite/mdbExtensionController.test.ts
This PR adds two tests to ensure the language server bundles exist.
This PR also cleans up our commands a bit, we were showing some of the commands from the tree view in the command palette, so now it won't show those. When we add future commands lets keep in mind to hide them from the command palette if we don't want them used there.
I'd like to clean up the commands a bit more and have them live in an a `commands.ts` file where they exist as variable we can reference. That can wait though.
Small text change on the create playground action in the tree view: 
(It was MongoDB: Create New Playground)
=> Add language server file dependency tests

src/test/suite/views/webviewController.test.ts, src/views/webview-app/components/app.tsx, src/views/webview-app/components/connect-form/connection-form.tsx, src/views/webview-app/extension-app-message-constants.ts, src/views/webview-app/store/actions.ts, src/views/webview-app/store/store.ts, src/views/webviewController.ts
https://jira.mongodb.org/browse/VSCODE-87
This PR adds a message on successful uri connection to the connection form just for some visual feedback. It does not show anything if the connection event was unsuccessful (vscode shows an information message for that in the bottom left). The message is hidden when connect with uri is clicked again, or an action is done on the form. We can give more feedback later on, I thought this will be a nice quick solution for now. Claudia has some thoughts/designs for this connect form so there's a good change this will change around.
=> VSCODE-87: Add message when successful uri connection

package-lock.json, package.json, src/editors/playgroundController.ts, src/language/languageServerController.ts, src/language/mongoDBService.ts, src/language/visitor.ts, src/test/suite/language/mongoDBService.test.ts
- Allow collection names completion in the middle of expression `db..find()`
- Convert collection name with dashes to array like format in the middle of expression `db.coll-name.find()` ->  `db['coll-name'].find()`
- Provide only collection names in the middle of expression (not shell methods)
- Provide cursor methods only after `find()` and `aggregate()`, not inside objects
- Use different icons for collection names and db methods suggestions
- Refactor Visitor class to use visit node methods instead of multiple condition statements in the AST parsing method
- Disable completions after disconnecting
- Provide collection names completion in variable declarations `const a = db.`
- Provide only collection names and shell db symbol completion after using a cursor and then using `db.`
- …
=> Vscode 102 coll names completion improvement

package.json
This PR removes a couple commands from the command palette which we are only using in the tree view.
=> Remove duplicate add connection command palette commands

README.md
`npm run local-install` fails on windows, so this adds a note to `Installing the
extension from sources` for a windows build.
=> add a note on local windows installation

package.json, src/editors/collectionDocumentsCodeLensProvider.ts, src/editors/documentProvider.ts, src/mdbExtensionController.ts
The `showMoreDocumentsClicked` receives a list of arguments. The behavior of this changed where its not passing the 2nd and 3rd arguments. This PR passes them all in the first argument to ensure vscode passes them correctly.
I'll write a quick test so this can't break in next pr.
Also in this pr, we hide the command `showActiveConnectionInPlayground` from the command palette since it's an internally used command.
Created https://jira.mongodb.org/browse/VSCODE-112 for better error messaging when disconnected.
=> Fix show more documents code lens argument passing

src/extension.ts
https://jira.mongodb.org/browse/VSCODE-90
Currently we're outputting all (`*`) logs with the `debug` module.
This PR updates our logging namespaces to just `INFO`, `ERROR`, and `WARN`. This will silence the `DEBUG` logs which contain the heartbeats and some of the other connection messages. 
I'm looking into best practices for extension logging now, this update should at least put us in a better spot in terms of reporting messages with less credentials in them.
=> VSCODE-90: Remove heartbeats from logger

src/connectionController.ts, src/editors/playgroundController.ts, src/mdbExtensionController.ts, src/telemetry/telemetryController.ts, src/test/suite/connectionController.test.ts, src/test/suite/editors/activeDBCodeLensProvider.test.ts, src/test/suite/editors/collectionDocumentsProvider.test.ts, src/test/suite/editors/documentProvider.test.ts, src/test/suite/editors/playgroundController.test.ts, src/test/suite/explorer/explorerController.test.ts, src/test/suite/extension.test.ts, src/test/suite/index.ts, src/test/suite/language/languageServerController.test.ts, src/test/suite/mdbExtensionController.test.ts, src/test/suite/telemetry/telemetryController.test.ts, src/test/suite/views/webviewController.test.ts, src/views/webviewController.ts
Add tests for the `new connection` event.
=> VSCODE-113: Add tests for the new connection event

README.md, src/connectionController.ts, src/telemetry/telemetryController.ts, src/views/webviewController.ts
Adjusted telemetry events in accordance with MDB naming convention.
=> Telemetry events naming convention

src/test/suite/views/webviewController.test.ts, src/views/webview-app/connection-model/connection-model.ts, src/views/webviewController.ts
https://jira.mongodb.org/browse/VSCODE-117
Our file paths are relative to the file system (/ at the beginning), when they're read in with node https://github.com/mongodb-js/connection-model/blob/master/lib/connect.js#L42 they are resolved in a way that was adding an extra system /. Linux handled this alright but on windows we were getting errors like `Cannot read file 'C:/C:/some_path_to_file.file'`. This fix just removes the leading / so they can resolve correctly in connect.
Tested manually on windows & linux opening CA & SSH files. Still thinking about how we can best integrated test ssl and ssh auth as they've been breaking points here and in compass.
Removed a bit of unused url code in connection model as well.
=> VSCODE-117: Fix file pathing for windows connect

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
Remove invalid characters from templates to enable them on GitHub.
=> Fix: remove invalid characters from templates

src/explorer/mdbConnectionsTreeItem.ts, src/test/suite/explorer/explorerController.test.ts
https://jira.mongodb.org/browse/VSCODE-127
This PR adds a sort to connections in the tree view so they are shown alphabetically.
=> VSCODE-127: Sort connection tree items by label

package-lock.json, package.json
https://jira.mongodb.org/browse/COMPASS-4278
This pulls in the readPreferenceTag fix on connection model which should fix urls with readPreferenceTag groups.
=> Bump connection model version to pull in reference tag fix

package.json, src/commands/launchMongoShell.ts, src/mdbExtensionController.ts, src/test/suite/commands/launchMongoShell.test.ts, src/test/suite/extension.test.ts, src/test/suite/views/webviewController.test.ts, src/views/webview-app/components/connect-form/connection-form.tsx, src/views/webview-app/components/connect-form/host/host-input.tsx, src/views/webview-app/components/connect-form/host/port-input.tsx, src/views/webview-app/store/store.ts, src/views/webviewController.ts
https://jira.mongodb.org/browse/VSCODE-115
This PR tweaks our usage of `createTerminal` so that we pass the `mongosh` arguments as part of the command. This lets us not have to set/unset environment variables, while keeping the connection string credentials not showing in plain text in the console. This will also help the shell run across platforms since we're not relying on shell syntax for any commands.
I think it would be nice to move the launching mongo shell and helpers into another file for organization. Didn't plan on doing it in this PR, we could though.
=> VSCODE-115: Launch mongoshell cross platform

azure-pipelines.yml
https://jira.mongodb.org/browse/VSCODE-116
This PR adds a filesize check in our pipeline to make sure the bundle stays under 5MB. It also adds the built .vsix as a build artifact so we can more easily test and share builds.
These docs are very useful: https://code.visualstudio.com/api/working-with-extensions/continuous-integration https://code.visualstudio.com/api/working-with-extensions/publishing-extension
Also doing a bit of double checking/cleanup with this PR.
- Going over our .vscodeignore
- Looking at easy wins for making our extension size a bit smaller / faster
To download the artifact that each build creates on linux:
On the azure pipeline page there's an artifacts link:
And then the download is in the dropdown on the right:
To publish, we have a token for the marketplace, so we …
=> VSCODE-116: Automate vscode publishing

azure-pipelines.yml, src/commands/launchMongoShell.ts, src/test/suite/commands/launchMongoShell.test.ts
Looks like the recent launch MongoDB shell work didn't cover `powershell.exe`, just `cmd.exe` windows shells. I thought I tested with powershell on the windows support ticket for this, I must have missed it or used a wrong version 😭  This PR adds custom support for powershell variable syntax.
Added tests for powershell and manually tested external connections on the 3 shells.
Bug report: https://github.com/mongodb-js/vscode/issues/142
=> Launch mongo shell powershell fix

package-lock.json, package.json, src/explorer/collectionTreeItem.ts, src/explorer/databaseTreeItem.ts, src/explorer/documentListTreeItem.ts, src/explorer/explorerTreeController.ts, src/language/mongoDBService.ts, src/mdbExtensionController.ts, src/test/suite/explorer/collectionTreeItem.test.ts, src/test/suite/explorer/databaseTreeItem.test.ts, src/test/suite/explorer/documentListTreeItem.test.ts, src/test/suite/explorer/documentTreeItem.test.ts, src/test/suite/explorer/explorerController.test.ts, src/test/suite/explorer/schemaTreeItem.test.ts, src/test/suite/extension.test.ts, src/test/suite/index.ts, src/test/suite/mdbExtensionController.test.ts, src/test/suite/stubs.ts
https://jira.mongodb.org/browse/VSCODE-56
This PR adds a document count in the tree view. The count is shown in the document lists' description. When the document count is a large number it's abbreviated using [numeral js](http://numeraljs.com/) (Compass also uses this). Chatted with Claudia and Max and we were preferring uppercase abbreviations over lowercase (`k` vs `K`, `m` vs `M`), so they're shown in uppercase, any thoughts? 
When the document list is hovered, the tooltip shows the full document count.
Also added a `Refresh` right-click action to the document list to reset it in the tree view.
___
=> VSCODE-56: Display document count in tree view

package.json, src/connectionController.ts, src/editors/activeConnectionCodeLensProvider.ts, src/editors/playgroundController.ts, src/explorer/databaseTreeItem.ts, src/mdbExtensionController.ts, src/test/suite/connectionController.test.ts, src/test/suite/editors/activeDBCodeLensProvider.test.ts, src/test/suite/explorer/databaseTreeItem.test.ts, src/test/suite/mdbExtensionController.test.ts, src/test/suite/telemetry/telemetryController.test.ts
Use code lenses to connect to the new or saved connection:
- If a user is not connected show code lenses with a disconnected message. The code lenses' message is a link that opens a command palette with a list of saved connections started with the 'Add new connection' item.
- Clicking on the 'Add new connection' item opens a quick input to enter a new connection string.
- Clicking on any other connection item starts the connection process to the selected connection.
- After connecting the code lenses message shows the current connection host and port.
- If the user is connected and click on the code lenses again the same connection will be shown to allow the user select another connection or create a new connection.
=> VSCODE-97: Connect with code lenses

src/connectionController.ts, src/explorer/mdbConnectionsTreeItem.ts, src/test/suite/connectionController.test.ts, src/test/suite/views/webviewController.test.ts, src/views/webview-app/components/app.tsx, src/views/webview-app/components/connect-form/connection-form.tsx, src/views/webview-app/components/connect-form/form-actions.tsx, src/views/webview-app/extension-app-message-constants.ts, src/views/webview-app/store/actions.ts, src/views/webview-app/store/store.ts, src/views/webviewController.ts
VSCODE-155
This PR adds versioning to connecting so that a new connection can be attempted while there's already a connection in progress. Only the most recent connection attempt will successfully open the connection to be used.
This PR also allows users to remove connections while they're currently connecting. I think this PR adds a bit of complexity to how we connect to new connections and disconnect, so there can be some risk of introducing a possible race condition in future, it's something we should be aware of.
Something that happens sometimes when connecting to a connection is the connection string is misformed or the database is currently offline. In these cases we would freeze up for 30s waiting for the connection to resolve. This might confuse a user and is frustrating when it's …
=> VSCODE-155: Allow connecting to a new connection when already connecting

src/views/webview-app/components/connect-form/form-actions.tsx, src/views/webview-app/connect.module.less
Meant to be in PR https://github.com/mongodb-js/vscode/pull/156
=> Add improvements to connect form connect message styling

package.json, src/editors/playgroundController.ts, src/explorer/indexListTreeItem.ts, src/explorer/indexTreeItem.ts, src/mdbExtensionController.ts, src/templates/playgroundCreateIndexTemplate.ts, src/templates/playgroundSearchTemplate.ts, src/templates/playgroundTemplate.ts, src/test/suite/explorer/indexListTreeItem.test.ts, src/test/suite/explorer/indexTreeItem.test.ts, src/test/suite/extension.test.ts, src/test/suite/mdbExtensionController.test.ts
VSCODE-138
This PR adds a button and right click action to create a playground with a template to create an index quickly. The PR also adds a refresh indexes right click action. It also adds caching to the expanded state of indexes which should be nice (previously they'd collapse if a parent folder was expanded/collapsed).
How does the ensureIndex/createIndex playground template look? Went with `ensureIndex` instead of `createIndex`
*Using older template in gif*
=> VSCODE-138: Quick index creation

package.json, src/editors/playgroundController.ts, src/test/suite/editors/playgroundController.test.ts
We display the play icon to run a playground only for .mongodb files. But we also have a possibility to trigger playground running events by using a command palette or shortcuts. In this case, a user can try to run a non-mongodb file or even start running a playground when no playgrounds open. It will try to run the last open playground. We should display playground running commands in the command palette only when mongodb file is open and show the running error for other file extensions or when the playground not found.
=> VSCODE-174: Run only mongodb files when using shortcuts or command palette

src/editors/playgroundController.ts
Change the logic to show code lenses above the selected block of text instead of showing them below the selection. According to VSCode API code lenses always appear above the specified line, therefore if there is no empty line below the selected block of text, there is no entry point for code lenses to appear above and code lenses are missing.
=> VSCODE-175: show code lenses before a playground block

src/test/suite/views/webviewController.test.ts, src/views/webviewController.ts
VSCODE-123
Instead of loading the connect form's webview js file as a `vscode-resource:` URI we now use the URI created from `asWebviewUri`.
Addresses: https://github.com/mongodb-js/vscode/issues/102
=> VSCODE-123: Use asWebviewUri to load our bundled webview js file

src/editors/playgroundController.ts, src/test/suite/editors/playgroundController.test.ts
A playground file might already be open at the time the
`PlaygroundController` is created.
---
Not sure how to add tests for this, the existing ones for `playgroundController` don’t really seem to account for this type of scenario?
=> VSCODE-180 - Account for playground files from previous session

src/test/suite/views/webview-app/components/connection-status/connection-status.test.tsx, src/test/suite/views/webviewController.test.ts, src/views/webview-app/components/connection-status/connection-status.less, src/views/webview-app/components/connection-status/connection-status.tsx, src/views/webview-app/components/info-sprinkle/info-sprinkle.less, src/views/webview-app/extension-app-message-constants.ts, src/views/webview-app/store/actions.ts, src/views/webview-app/store/store.ts, src/views/webviewController.ts
VSCODE-189
This PR adds a rename connection button to the overview page next to your active connection name (pencil icon).
Also two smaller styling updates after chatting with Alena & Claudia: updated playground message font size 20->18px and hover color on the info icon.
_Light mode_
=> VSCODE-189: Add rename connection button to overview page

src/explorer/helpTree.ts, src/test/suite/explorer/helpExplorer.test.ts, src/test/suite/utils/linkHelper.test.ts, src/utils/linkHelper.ts
This constitutes the prep work to eventually introduce a sign-in/sign-up functionality for Atlas.
By using a short-lived local server, we can redirect the user to the right Atlas sign-in/up page and wait for an auth redirect in VS Code.
~I have a test that is currently commented out that I don't know how to make pass.~
=> Atlas sign-in/up uses a localhost redirect

src/test/suite/utils/linkHelper.test.ts, src/utils/linkHelper.ts
Restricts the redirects done by the short-lived helper server to a list of trusted domains.
=> Only allow redirects for mongodb.com domains

package.json, src/editors/editorsController.ts, src/editors/playgroundController.ts, src/editors/playgroundResultProvider.ts, src/language/mongoDBService.ts, src/language/worker.ts, src/mdbExtensionController.ts, src/telemetry/telemetryController.ts, src/test/suite/editors/playgroundController.test.ts, src/test/suite/language/mongoDBService.test.ts, src/test/suite/stubs.ts, src/test/suite/telemetry/telemetryController.test.ts, src/utils/types.ts
- Move playground results from the output channel to the virtual document opened in a split-view mode.
- The results of a playground should have syntax highlighting if they represent a JSON document.
- The results that are not Ja SON document should be printed as plain text with a single color.
- Users can open as many playgrounds they want, but results should be always printed to the same Results editor.
- The Results editor can be drag and dropped to any side of a split-view mode and should keep receiving results from any opened playground. 
- The Results file can be saved on a disc and in this case the current Results file stops acting as a Results editor and the new Results editor will be open with the next successful playground execution. It will allow users to freeze some results …
=> VSCODE-177: display playground output in editor

src/commands/launchMongoShell.ts, src/test/suite/commands/launchMongoShell.test.ts
VSCODE-200
Fixes https://github.com/mongodb-js/vscode/issues/186
This PR adds support for launching MongoDB shell when the user has their default shell set to git bash.
It also fixes an issue with loading files with spaces in them.
The way we do the environment passing for these different shell environments is a bit manual and hacky. I've looked around for a bit for a node package which provides support for building the shell command for various shells/environments but haven't found one. Do ya'll know of one? I think this works for now but it would be nice to have a quick catch all to prevent any lack of support for other environments.
Manually tested with SSL certs on windows (with a cert file with a space in it which is how I came across that other bug xD).
=> VSCODE-200: Open mongodb shell with git bash

package-lock.json, package.json
VSCODE-202
Pulls in https://github.com/mongodb-js/connection-model/pull/327/files
=> fix(VSCODE-202): Allow x509 username to be optional in connection string parsing and building

src/test/suite/views/webview-app/components/connect-form/general-tab/authentication/authentication.test.tsx, src/test/suite/views/webview-app/components/form/radio-box-group/radio-box-group.test.tsx, src/views/webview-app/components/connect-form/advanced-tab/read-preference-select.tsx, src/views/webview-app/components/connect-form/general-tab/authentication/authentication.tsx, src/views/webview-app/components/connect-form/ssh-tab/ssh-tunnel-tab.tsx, src/views/webview-app/components/form/radio-box-group/radio-box-group.less, src/views/webview-app/components/form/radio-box-group/radio-box-group.tsx, src/views/webview-app/connection-model/constants/ssh-tunnel-types.ts, src/views/webview-app/connection-model/constants/ssl-methods.ts
VSCODE-197
This PR updates some of our select items in the connection form to use a new radio box group.
We haven't updated the SSL options yet since we're still actively discussing how they'll look.
Here's a gif of the form. At the end it demos using keys to select different items, showing the focus state.
*light theme (blue box shadow shows focus)*
=> feat(VSCODE-197): Add radio box group to update connect form select options

src/templates/playgroundCreateIndexTemplate.ts
TIL `ensureIndex` is deprecated 😅 
https://docs.mongodb.com/manual/reference/method/db.collection.ensureIndex/
=> fix: use `createIndex` instead of deprecated `ensureIndex`

src/views/webview-app/components/atlas-cta/atlas-cta.less, src/views/webview-app/components/atlas-cta/atlas-cta.tsx, src/views/webview-app/components/resources-panel/resources-panel.less, src/views/webview-app/components/resources-panel/resources-panel.tsx, src/views/webview-app/connect.module.less
VSCODE-168 This PR has a few styling updates to the resources panel and overview page following chats with Claudia (@Sgrinfy ) 
It adds default focus outline color and link highlight color to the overview page for some nicer styles throughout.
Updates in the resources panel:
- we now keep with width constant, so the opening animation looks smoother
- link hover color is now green
- more spacing between elements to reflect the mocks
- add the arrow icon to the big links
=> feat(VSCODE-168): Improve resources panel styling

src/views/webview-app/components/connect-form/ssl-tab/ssl-tab.tsx
This PR changes our SSL Tab to use the box group select component instead of the select dropdown.
This PR does remove our last reference to the select component, so it isn't used in the form anymore. I didn't remove it from the codebase because it is included in the mocks so we'll be using it later. If preferred I can remove it for now and add it back in later.
=> feat(connect-form): Update ssl tab to use box group select instead of select dropdown

package-lock.json, package.json, src/editors/documentProvider.ts, src/editors/editorsController.ts, src/explorer/documentTreeItem.ts, src/test/suite/editors/documentProvider.test.ts, src/test/suite/editors/documentStringFixtures.ts
VSCODE-118
Previously only object ids and primitives were able to be open.
This fixes part of https://github.com/mongodb-js/vscode/issues/131 however it looks like we can't hand numberLong types over a certain amount, which is a separate issue.
*The first document opened in gif*
Also found out that Compass doesn't allow editing binary - or numberLong - values except in the json view, however when it's edited in the json view it silently fails. Need to see if a ticket already exists.
=> fix(VSCODE-118): Fix opening documents with binary _id from tree view

src/test/suite/connectionController.test.ts, src/test/suite/explorer/fieldTreeItem.test.ts, src/test/suite/explorer/playgroundsExplorer.test.ts, src/test/suite/explorer/schemaTreeItem.test.ts, src/test/suite/mdbExtensionController.test.ts, src/test/suite/telemetry/telemetryController.test.ts
I ran tests for this a few dozen times in a loop and they did not fail
this way.
Changes include:
- A few timeout increases that otherwise were triggered locally for me
- Using a different `connectionId` for a specific test in the
connection controller tests to avoid possible conflicts with other
tests
- Printing more details in case of failure for one test that failed
once but that I could not reproduce again.
=> chore(test): make tests more resilient VSCODE-209

src/connectionController.ts, src/test/suite/connectionController.test.ts, src/test/suite/views/webview-app/store/store.test.ts, src/test/suite/views/webviewController.test.ts, src/views/webview-app/components/app.tsx, src/views/webview-app/extension-app-message-constants.ts, src/views/webview-app/store/actions.ts, src/views/webview-app/store/store.ts, src/views/webviewController.ts
VSCODE-196
This PR updates how we show errors in our connection form. Previously we would show descriptive errors in vscode alerts. This updates the behavior to make the error in the connection form the verbose one, and move away from showing verbose vscode notifications, to show the error in the form ui. 
Wrapped a bit of cleanup in too, previously we were storing the connecting connection identifier as a number, now we use a uuid or the connection's id. The connection form now also stores the connecting connection identifier, so it can ignore overridden connection attempt results.
This PR should also handle the case where the user has closed the form window where they are attempting to connect. Previously this would cause a silent background error.
=> feat(VSCODE-196): Show connection form error in connection form

package-lock.json, src/editors/documentIdStore.ts, src/editors/documentProvider.ts, src/editors/editorsController.ts, src/editors/playgroundController.ts, src/test/suite/editors/documentProvider.test.ts, src/test/suite/editors/documentStringFixtures.ts, src/test/suite/editors/playgroundController.test.ts, src/test/suite/mdbExtensionController.test.ts, src/test/suite/stubs.ts, src/utils/types.ts
The solution introduced in https://github.com/mongodb-js/vscode/pull/213 didn't fully cover all the opening of documents with different typed `_id` cases. When we open documents in vscode, in the original solution we sort of hackily added the _id as a ejsoned string on the document's uri in vscode. This doesn't work well because we have to ejson stringify, parse, uri encode, uri decode, and also we're bound by uri constraints like character limits in the query.
This PR updates how we pass a document's `_id` to the [document provider in vscode](https://code.visualstudio.com/api/extension-guides/virtual-documents#:~:text=Document%20providers%20are%20first%20class,they%20are%20part%20of%20vscode.). It adds a store which we then pass a reference to, so that we can avoid any encoding/decoding …
=> fix(VSCODE-118): Fix opening binary _id

src/connectionController.ts, src/test/suite/connectionController.test.ts
VSCODE-209
I think this should fix the flaky test by making the timer on connecting a set amount. It's a bit of a weird test, but it does test important behavior.
=> fix(VSCODE-209): update flaky test to use timers

README.md, package.json, src/commands/index.ts, src/dataServiceType.ts, src/editors/collectionDocumentsProvider.ts, src/editors/documentIdStore.ts, src/editors/documentProvider.ts, src/editors/editorsController.ts, src/mdbExtensionController.ts, src/test/suite/mdbExtensionController.test.ts
Edit documents that are opened from the tree-view.
- When a document is opened from the tree-view, the document is editable.
- Each document should be opened as a separate editor.
- Each document should be opened only once.
- If a user didn't make any changes the document can be simply closed without a confirmation modal.
- Editing happens in EJSON to preserve type information.
- When the document is saved (Cmd/Ctrl + S), the document is updated in MongoDB to reflect the changes that were made.
- For saving documents we use findOneAndReplace.
- When the document is saved, a notification informs the user that the change has been saved in MongoDB.
- When the update results in an error, the user is notified.
- It's possible to make edits to a document and save it more than once.
- When the …
=> VSCODE-219: edit documents opened form the sidebar

.vscode/extensions.json
This PR updates our recommended extension's development extensions to remove `tslint` and add `eslint`. This should hopefully reduce some of the reformatting changes that were occurring (you might need to remove the `tslint` extension manually if it's already installed). 
See https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions for more info on this file.
=> chore(dev-deps): Update tslint to eslint extension

src/views/webview-app/components/connect-form/connection-form.less, src/views/webview-app/components/connect-form/general-tab/general-tab.tsx, src/views/webview-app/components/form/divider/divider.less, src/views/webview-app/components/form/divider/divider.tsx, src/views/webview-app/components/form/radio-box-group/radio-box-group.tsx
Adds divider to separate host info from authentication.
Updates the styling on the connection tabs (there was a 1px space between the bottom of the active state and the divider). Kinda of hard to see but a bit easier to see on other color themes.
=> styling(connect-form): add divider, tweak tabs overflow

src/editors/editDocumentCodeLensProvider.ts, src/test/suite/editors/editDocumentCodeLensProvider.test.ts, src/test/suite/editors/mongoDBDocumentService.test.ts
Data service's `find()` does not accept ids in ejson format (e.g. `_id: {$oid: ‘5d973ae744376d2aae72a160’}`) and throws the following error:
Deserialize document id before fetching a document to make sure id is `BSON.ObjectId()`.
=> fix: deserialize document id before fetching document

src/telemetry/telemetryService.ts, src/test/suite/telemetry/telemetryService.test.ts
VSCODE-126
Adds the extension version to the connection telemetry event.
Also adds a test w/ a real database for instance detail since I think we didn't have one before.
=> chore(telemetry): Add extension version to connected event VSCODE-126

src/explorer/helpTree.ts, src/test/suite/explorer/helpExplorer.test.ts, src/test/suite/views/webview-app/components/atlas-cta/atlas-cta.test.tsx, src/views/webview-app/components/atlas-cta/atlas-cta.tsx
Adjusted the Atlas links to go to a `https` page and tweaked the copy in CTA after chatting with product marketing.
=> Changed Atlas links to https and adjused CTA copy

package.json, src/explorer/collectionTreeItem.ts, src/explorer/documentListTreeItem.ts, src/test/suite/explorer/documentListTreeItem.test.ts, src/test/suite/mdbExtensionController.test.ts
This PR adds an icon to the documents list to refresh them.
Motivation https://feedback.mongodb.com/forums/929236-mongodb-for-vs-code/suggestions/42462064-refresh-button-or-automatic-refresh-for-the-collec
Would like to revisit how we structure/render all of the tree elements, it could be done in a cleaner way. Works though, maybe in a later pr.
https://user-images.githubusercontent.com/1791149/108073087-f0461800-7067-11eb-8cee-525ca7392828.mp4
=> feat: Add icon for collection documents list refresh

package-lock.json, package.json, src/language/mongoDBService.ts, src/test/suite/language/mongoDBService.test.ts
Given that we are pulling the autocomplete symbols from the shell API, we can pull the documentation details from there too.
This change pulls in the shell's `i18n` package and uses that to enrich the shell `CompletionItem`s with an example and a one-sentence explanation of what the command does. Unfortunately it does not look like the CompletionItem API supports links.
That string that is passed to `Translator.translate()` is overly verbose but there does not seem to be a way around that.
=> Autocomplete details

src/test/suite/mdbExtensionController.test.ts
We can’t modify a frozen object, which `vscode.env.clipboard` has
recently become.
Refs: https://github.com/microsoft/vscode/commit/4cfd5f850806fd293d5ca6e988c612a5514f93b3#diff-635fc88732ee6c5c620c7b69dc4b9a56ba478d96505aec360fce3d6fa6b8c314
=> fix: make tests work with changed vscode clipboard object VSCODE-241

src/templates/playgroundTemplate.ts
Updates the playground template aggregation to have a comment for `.toArray` and explicitly note that a cursor is currently created. Thinking it might help cases like https://github.com/mongodb-js/vscode/issues/273
=> fix: update playground template to add a comment for .toArray to aggregation run

src/explorer/collectionTreeItem.ts, src/explorer/connectionTreeItem.ts, src/explorer/databaseTreeItem.ts
Fixes the issue with dropped collections and databases still being displayed in the explorer tree view due to cache still keeping a reference to them. This PR addresses the issue by introducing new `isDropped` property for db/coll that their parent tree view can use to prune cache on refresh
=> fix(explorer): Mark dropped db/coll tree item; Do not re-create dropped items in children cache VSCODE-244

src/editors/editorsController.ts, src/editors/playgroundController.ts, src/test/suite/editors/editorsController.test.ts, src/test/suite/editors/playgroundController.test.ts
1) Preserve focus after running playgrounds to be able quickly to make additional changes and run the playground again: https://jira.mongodb.org/browse/VSCODE-214
- Related issue: https://github.com/mongodb-js/vscode/issues/222
- Note: We made a decision to preserve focus by default and do not make it configurable in settings.
2) For large files VSCode turns off tokenization, wrapping, and folding in order to reduce memory usage and avoid freezing or crashing. This causes situations when the file is open, but the `vscode.window.activeTextEditor` is `undefined`. This PR removes throwing an error when there is no active editor and keeps the default behavior for such files, that is saving files to disc: https://jira.mongodb.org/browse/VSCODE-250
=> fix: save big files without error and preserve playground focus

snippets/atlas-terraform.json, src/explorer/databaseTreeItem.ts, src/test/suite/explorer/databaseTreeItem.test.ts, src/test/suite/stubs.ts
To separate system collections from regular collections, we display them last in the list.
This PR also includes a minor tweak to the Terraform snippet as one line was not properly indented.
=> feat: system collections are last in the list

package-lock.json, package.json, src/language/visitor.ts, src/test/suite/language/mongoDBService.test.ts
=> fix: remove `any` usage and fix invalid accesses in autocompletion

src/explorer/helpTree.ts, src/telemetry/telemetryService.ts, src/test/suite/explorer/helpExplorer.test.ts, src/test/suite/telemetry/telemetryService.test.ts
Follow up on https://github.com/mongodb-js/vscode/pull/302 since there's another link spot I missed.
Attach anonymous ID of user to the url of the cta link to Atlas VSCODE-249
=> chore: Add segment telemetry id to create atlas cluster

src/explorer/collectionTreeItem.ts
VSCODE-268
Small change to quietly handle when getting the estimated count on a collections fails, since views and time-series collections error with `estimatedDocumentCount`.
=> fix(tree-explorer): dont show message when cannot fetch estimated count VSCODE-268

.vscode/settings.json
That setting gave me a few headaches since VSCode was formatting the code in a way eslint didn't like.
I suggest to replace it with something more true to our style rules. ... also dropping the auto save entirely unless we find it super useful wouldn't be all that bad.
=> chore: replace formatOnSave with fixAll.eslint

.github/workflows/publish-release.yaml, .github/workflows/rebuild-changelog.yaml, .github/workflows/test-and-build.yaml, package-lock.json, package.json, scripts/release-draft.js, src/test/suite/connectionController.test.ts
Automate the release of the extension
When the build is triggered with a tag `v*.*.*`:
- The extension `CHANGELOG.md`, the one visible in the Settings panel, is replaced with a link to the Github release
- The `package.json` and `package-lock.json` versions are set to the tag version
- A draft release is built with the `vsix` bundle attached
When the release is published:
- The `vsix` asset is downloaded from the release and uploaded to the vscode marketplace 
- The `CHANGELOG.md` in the root of the repo is regenerated and pushed to main
=> chore: automate release VSCODE-116

package-lock.json, package.json, src/explorer/connectionTreeItem.ts, src/test/suite/dbTestHelper.ts, src/test/suite/explorer/connectionTreeItem.test.ts, src/test/suite/stubs.ts, src/types/connectionModelType.ts, src/types/dataServiceType.ts
VSCODE-157
This PR makes it so that we show databases in the tree view that a user might be able to use, even if that user doesn't have the ability to `listDatabases`. To do this we're fetching the privileges for the currently authenticated user, and using the db names found there to populate the database list. The user will still need access to `listCollections` to use the database in the connection tree explorer, but at least the database will be shown.
Should address https://github.com/mongodb-js/vscode/issues/96
For reference:
https://docs.mongodb.com/manual/tutorial/manage-users-and-roles/
https://docs.mongodb.com/compass/master/connect/required-access/#required-access
Creating a role and user restricted to database `aa` (Be sure to start `mongod` with `--auth` or authorization …
=> feat(data-explorer): Add support for solo db users VSCODE-157

.github/workflows/publish-release.yaml, .github/workflows/rebuild-changelog.yaml, .github/workflows/test-and-build.yaml
Fixes a couple issues on building/releasing/building changelog. 
Updated our release version title to have a `v` in the front, this is mostly since our previous release titles are named like that. I read somewhere it's a recommended practice, but I think it could probably go either way - any preferences?
=> fix(ci): fix release github actions

src/editors/partialExecutionCodeLensProvider.ts, src/editors/playgroundController.ts, src/test/suite/editors/playgroundController.test.ts
Chatting and pairing on this w/ @alenakhineika - we were thinking until we decide if code actions are a better alternative we could go back to putting the code lenses at the bottom of selections just to hopefully improve that ux.
This PR has a few fixes for situations where we weren't showing codelenses, for instance if a user had a multi selection and the last selection was an empty space it wouldn't show a code lens.
In cases where the selection includes the end of the playground, and that last line is not empty, we now add an empty line so we can show a code lens nicely at the end. This is shown in the video below. I don't totally remember, but I think this maybe have been the reason we changed to putting code lenses on top.
https://user-images.githubusercontent.com/1791149/126701660-93 …
=> feat(playgrounds): Show code lens at end of selection

.github/workflows/publish-release.yaml
fixes `ERROR  end of central directory record signature not found`
=> fix(ci): use wget instead of curl for asset dl

.github/workflows/publish-release.yaml, CHANGELOG.md, README.md, src/explorer/helpTree.ts, src/telemetry/telemetryService.ts
VSCODE-281
We now supply the `--githubBranch main` option to `vsce publish` so that the generated README at https://marketplace.visualstudio.com/items?itemName=mongodb.mongodb-vscode has correct addresses for the referenced images (currently they're defaulting to `master` and not loading images).
You can view the `vsce publish` options here: https://github.com/Microsoft/vscode-vsce/blob/main/src/main.ts#L136
=> fix(ci): make published readme reference main branch instead of master

.github/workflows/test-and-build.yaml, package-lock.json, package.json
VSCODE-281
Follow up to https://github.com/mongodb-js/vscode/pull/331 - didn't fix it because it happens at the `vsce package` step, not the published. Also bumped `vsce` version since ours was a bit behind.
This fixes the images referencing `master` instead of `main` in the generated README used in the vscode marketplace: https://marketplace.visualstudio.com/items?itemName=mongodb.mongodb-vscode
=> fix(ci): set githubBranch to main when packaging extension VSCODE-281

src/templates/playgroundCreateCollectionWithTSTemplate.ts
VSCODE-291
Added `granularity: <string>`, could also add a comment or write it as `granularity: <"seconds"|"minutes"|"hours">` any preferences? Fine as it is?
https://docs.mongodb.com/manual/core/timeseries-collections/
=> chore(playgrounds): Update create collection time-series template VSCODE-291

src/test/suite/views/webviewController.test.ts, src/views/webviewController.ts
VSCODE-284
Fixes opening files on wsl. Remove the resolving of the file path, since it's resolved later. Not sure why we were doing it, looks like something I introduced lol. Maybe it was needed for the connection model & driver at the time.
Tested manually on wsl & mac w/ a tls file.
https://user-images.githubusercontent.com/1791149/131749631-8c5e905b-5591-4bef-9c5e-5452b01bbf6f.mp4
=> fix(connect-form): fix wsl file path resolving VSCODE-284

src/language/mongoDBService.ts
VSCODE-292
PR removes loading the files of tls/ssl files. Now we just pass the file names. I think we were doing this because of previous driver behavior, after we updated the driver in the latest release this probably broke.
Tested on mac w/ server+client and x509
Before releasing we should make sure we have this in the testing matrix and test it (I must have missed in it in the last release). 
We could probably add some nice e2e connectivity tests w/ playgrounds following the current Compass work.
Connecting + running a playground:
=> fix(language-server): remove loading ssl/tls files to just passing file names VSCODE-292

package-lock.json, package.json, src/test/suite/views/webviewController.test.ts, src/views/webviewController.ts
We were using `path` instead of `fsPath` which was resolving incorrectly on windows.
Tested manually w/ window, ubuntu, and mac connecting w/ x509 pem file.
Would be nice to find a way to test this dialog resolving using the different systems in our ci.
https://code.visualstudio.com/api/references/vscode-api#Uri
=> fix(connect-form): Update file path resolve to use fsPath instead of path

.github/workflows/test-and-build.yaml, package-lock.json, package.json
Tried the same thing to verify that CI behaves identically: https://github.com/mongodb-js/vscode/pull/378
Since each time we install the latest npm version we need to remember to unset global installed node-gyp: https://github.com/nodejs/node-gyp/blob/master/docs/Force-npm-to-use-global-node-gyp.md
The patch for node-gyp on Windows was added here: https://github.com/mongodb-js/vscode/pull/318
=> build: try to bump mongodb-ace-autocompleter version

.github/PULL_REQUEST_TEMPLATE.md, README.md, src/connectionController.ts, src/test/suite/connectionController.test.ts
- N/A New tests and/or benchmarks are included
- N/A Documentation is changed or added
* Mostly just fixes typos in the README that bothered me.
* windows → Windows
* Commmand → Command
* MacOS → macOS
* Fixes a typo in the pull request template.
* dependancy → dependency
* Removes a redundant line break in the README.
* Removes redundant assignment to `connections`, it's never used after that line anyway?
* `СonnectionQuickPicks` != `ConnectionQuickPicks`. I'm surprised the former is even a valid name in JavaScript. 🤔 It uses a Unicode character instead of an actual `C`.
I recommend you review the `ConnectionQuickPicks` yourself! 2 quick ways you can prove the difference though is:
1. CTRL + F and search one of them, and you'll find only one side of the diff will get highlighted.
2. If …
=> chores: fix typos in code and readme

README.md, package.json, src/commands/index.ts, src/mdbExtensionController.ts, src/test/suite/extension.test.ts, src/test/suite/utils/objectIdHelper.test.ts, src/utils/objectIdHelper.ts
* Closes https://github.com/mongodb-js/vscode/issues/415
Adds 2 commands and 1 configuration setting.
`mdb.insertObjectIdToEditor` - Generates an ObjectId and inserts it to the editor.
`mdb.generateObjectIdToClipboard` - Generates an ObjectId and saves it to the clipboard.
`mdb.uniqueObjectIdPerCursor` - If we should use the same or unique ObjectId when `mdb.insertObjectIdToEditor` is called with multiple cursors/selections.
Not really a problem, but I'd just find it pretty convenient if I could generate and insert ObjectIds into the editor through a command.
This is usually while creating fixtures for testing or sharing examples of models.
=> feat: add command to generate objectid

src/explorer/helpExplorer.ts
VSCODE-343
Doesn't need to be in release notes as the bug wasn't released. Looks like we added an extra `registerTreeDataProvider` to the help tree although it is already registered in the previous lines when we pass the `treeDataProvider` to `createTreeView`. This resulted in it not handling the tree selections (no link clicks). 
https://github.com/mongodb-js/vscode/pull/437/files#diff-9bc69eef7e7b5c6202fdac33a5f439e7ca8be35d80a56724d4b49b3e6c7f38f6R26
More on tree data providers: https://code.visualstudio.com/api/extension-guides/tree-view#registering-the-treedataprovider
=> fix(help-explorer): remove extra data provider tree register VSCODE-343

package.json, src/commands/index.ts, src/editors/editorsController.ts, src/editors/mongoDBDocumentService.ts, src/explorer/documentListTreeItem.ts, src/explorer/documentTreeItem.ts, src/mdbExtensionController.ts, src/test/suite/editors/mongoDBDocumentService.test.ts, src/test/suite/explorer/documentListTreeItem.test.ts, src/test/suite/explorer/documentTreeItem.test.ts, src/test/suite/extension.test.ts, src/test/suite/mdbExtensionController.test.ts, src/test/suite/stubs.ts
VSCODE-348
Add `Open Document` and `Copy Document` document context menu actions (right click).
https://user-images.githubusercontent.com/1791149/197725480-868ca5dd-1092-4f6d-a512-e4826d96599b.mp4
=> feat(tree-explorer): Add open and copy document tree view context menu items VSCODE-348

src/editors/playgroundController.ts
Previously we were updating the code actions on each character type as that would fire the selection change. This pr makes it only update the code actions when the selection's content changes.
=> chore(playgrounds): avoid export to language code actions refresh when nothing to refresh

README.md, package.json, src/commands/index.ts, src/connectionController.ts, src/explorer/documentListTreeItem.ts, src/explorer/documentTreeItem.ts, src/mdbExtensionController.ts, src/test/suite/explorer/documentTreeItem.test.ts, src/test/suite/extension.test.ts, src/test/suite/mdbExtensionController.test.ts
VSCODE-349
This adds a setting `confirmDeleteDocument` which defaults `true` to show a confirmation when deleting a document. Can add more tests if folks would like that.
https://user-images.githubusercontent.com/1791149/204882698-a93218c1-4933-4769-b38c-84c62715f501.mp4
=> feat(tree-explorer): add delete document context menu item VSCODE-349

src/editors/collectionDocumentsProvider.ts, src/editors/editorsController.ts, src/editors/mongoDBDocumentService.ts
Improves the error messages by showing the connection name in a few error messages that occur when the connection has changed, previously we were showing the connection id which doesn't mean much to a user. In the edge case where the old connection was removed and no longer exists we default to showing `the connection` as the name.
| before | after | 
| - | - |
| ![Screen Shot 2022-12-01 at 1 24 30 PM](https://user-images.githubusercontent.com/1791149/205131588-aea151aa-f767-4207-8b56-58ae96f13929.png) | ![Screen Shot 2022-12-01 at 1 26 34 PM](https://user-images.githubusercontent.com/1791149/205131610-7e114c1c-d71f-4a2d-ab15-d81915911f5a.png) |
=> chore: improve disconnected action error messages

package-lock.json, package.json, src/commands/index.ts, src/editors/playgroundController.ts, src/explorer/documentTreeItem.ts, src/mdbExtensionController.ts, src/templates/playgroundCloneDocumentTemplate.ts, src/test/suite/extension.test.ts, src/test/suite/mdbExtensionController.test.ts, src/typings.d.ts
VSCODE-350
Adds a `Clone Document...` action to the tree view. This action opens a playground where the document is used in an `insertOne` command.
Also did a bit of type cleanup in one of the test files, we were previously casting sinon fakes to `any`.
Could add more tests testing this functionality if folks want.
Here's how it looks:
https://user-images.githubusercontent.com/1791149/206322464-7342634b-b12a-448f-ab7a-2ebdbdb7fb62.mp4
=> feat(tree-explorer): add clone document context menu item to document item in tree explorer VSCODE-350

playgrounds/out-of-memory-test.mongodb, src/editors/playgroundController.ts, src/language/languageServerController.ts, src/test/suite/editors/playgroundController.test.ts, src/test/suite/explorer/playgroundsExplorer.test.ts
VSCODE-269
This pr makes it so that when the playground worker running mongosh runs out of memory we re-initialize the language server so that subsequent playgrounds can be run. 
The pr adds a playground to the repository to be used for testing this functionality.
At first I was trying to catch an error the worker thread would throw but it seemed to happen at a higher level https://github.com/mongodb-js/vscode/blob/36cebd0f519e17d0c4533c04c05ad7e416a9f6a7/src/language/mongoDBService.ts#L151 I'm thinking the VSCode language server disposes any language servers that encounter an out of memory error and restarts them automatically. It throws a `Pending response rejected since connection got disposed` error which is what we look for.
=> fix(playgrounds): handle out of memory playground worker VSCODE-269

playgrounds/all-field-types.mongodb, src/test/suite/explorer/playgroundsExplorer.test.ts
Written by @lerouxb 
Figured this would be helpful for testing down the line so it makes sense to be in a code base.
Here's what the resulting document schema looks like in our view:
=> chore(playgrounds): add all types playground for type testing

.github/workflows/report-nightly-build-failures.yaml
I've completely missed the fact that `steps.trigger_type.outputs.trigger_type` isn't a built-in thing, and there is a good chance that I'm reading the wrong event. Probably isn't worth the effort to keep investigating further, I wuld give this a try and if it doesn't work we can just drop it
=> chore(ci): add missing output var in nightly build faiulres

src/telemetry/telemetryService.ts, src/test/suite/language/languageServerController.test.ts, src/test/suite/language/mongoDBService.test.ts
```
/Users/rhys/mongodb/vscode/src/telemetry/telemetryService.ts
133:29  warning  Unexpected sync method: 'readFileSync'  no-sync
/Users/rhys/mongodb/vscode/src/test/suite/language/languageServerController.test.ts
137:12  warning  Unexpected sync method: 'existsSync'  no-sync
/Users/rhys/mongodb/vscode/src/test/suite/language/mongoDBService.test.ts
38:12  warning  Unexpected sync method: 'existsSync'  no-sync
```
=> chore: get rid of eslint warnings

src/templates/playgroundCreateCollectionTemplate.ts
VSCODE-362
This PR adds new options (`bucketMaxSpanSeconds` and `bucketRoundingSeconds`), introduced in MongoDB 6.3, to time-series collection options in create-collection playground template.
=> feat(playground): adds new Time-Series options for collection creation in playgrounds VSCODE-362

src/templates/playgroundCreateIndexTemplate.ts
VSCODE-364
This PR adds makes creation of `columnstore` indexes more visible in index creation template. Additionally we also surface `columnstoreProjection` as available option, supported alongside `columnstore` indexes.
=> feat(playground): makes creation of columnstore indexes more visible in index creation template VSCODE-364

package.json, src/commands/index.ts, src/editors/playgroundController.ts, src/mdbExtensionController.ts, src/templates/playgroundInsertDocumentTemplate.ts, src/test/suite/mdbExtensionController.test.ts
VSCODE-367
Adds an `Insert Document...` tree view context action to collections to shortcut adding a document.
| before | after |
| --- | --- |
| <img width="367" alt="Screen Shot 2023-01-31 at 11 51 26 PM" src="https://user-images.githubusercontent.com/1791149/215967692-736108b3-7a6b-4a36-b002-e789888edeea.png"> | <img width="368" alt="Screen Shot 2023-01-31 at 11 53 32 PM" src="https://user-images.githubusercontent.com/1791149/215967778-143fd318-46e6-4572-9cd8-dc3f82cd886a.png"> |
| <img width="427" alt="Screen Shot 2023-01-31 at 11 51 20 PM" src="https://user-images.githubusercontent.com/1791149/215967707-46568da0-8dc6-4122-9fc7-408d364e38b5.png"> | <img width="383" alt="Screen Shot 2023-01-31 at 11 53 26 PM" src="https://user-images.githubusercontent.com/1791149/215967795-6b1c3a55-300d …
=> feat(tree-explorer): add insert document context menu action VSCODE-367

src/templates/playgroundTemplate.ts
VSCODE-337
Opening to open a discussion with the team on how we can best supply a playground template for folks.
The changes in this one are:
- Removed the drop collection call. I'm thinking it's something that's a bit risky to have in a default script. It's a useful command, but I don't think it's something folks want to have a possibility of accidentally running.
- Removed the _id number usage (so we default the _id to ObjectId).
- Changed how we use collection methods collection methods from db.sales.find  to db['sales'].find to reduce possible rough spots with folks that have spaces and dashes in their collection names. EDIT: Based on Anna's reply: https://github.com/mongodb-js/vscode/pull/470#discussion_r1097199338 I'm thinking let's update it to db.getCollection('sales'). instead. I …
=> feat(playgrounds): update playground template VSCODE-337

.github/PULL_REQUEST_TEMPLATE.md
I noticed that we did not have a checkbox to indicate that non-MongoDB contributors have signed the agreement, so I added it.
External contributors need to sign the CLA for their contribution to be accepted.
=> Added Contributor License Agreement checkbox to PR

.github/workflows/test-and-build.yaml, src/commands/index.ts, src/editors/editorsController.ts, src/editors/playgroundController.ts, src/editors/playgroundDiagnosticsCodeActionProvider.ts, src/language/diagnosticCodes.ts, src/language/mongoDBService.ts, src/language/server.ts, src/mdbExtensionController.ts, src/telemetry/telemetryService.ts, src/templates/playgroundTemplate.ts, src/test/suite/language/mongoDBService.test.ts, src/test/suite/telemetry/telemetryService.test.ts, src/types/playgroundType.ts
Add the VSCode Language Server [Diagnostics](https://code.visualstudio.com/api/language-extensions/programmatic-language-features#provide-diagnostics) feature to highlight the usage of commands that only works inside interactive sessions. We've seen folks try to use Shell syntax that doesn't work in playgrounds like `show dbs;` or instead of using the correct `use('database_name')` people type `use database_name` which only works in the Shell and not playgrounds.
The diagnostic not only highlights the incorrect syntax but also offers quick fixes for the current problem and for all similar problems in the file.
Currently, the following fixes are available (the complete list is [here](https://www.mongodb.com/docs/mongodb-shell/reference/access-mdb-shell-help/)):
```js
[
{ issue: 'use', fix: …
```
=> feat: add diagnostics feature to the language server VSCODE-375

src/language/visitor.ts, src/test/suite/language/mongoDBService.test.ts
Provide shell methods completion after a collection specified as `getCollection()`.
Implements: https://github.com/mongodb-js/vscode/pull/417
=> feat: provide shell methods completions after getCollection VSCODE-390

README.md
=> docs: document the semantic highlighting issue VSCODE-374

src/explorer/connectionTreeItem.ts
We only use the database here so passing `nameOnly` should give a speedup.
Part of VSCODE-361
This also fixes an issue where the database names aren't showing for free tier instances (or maybe specific admin roles). Haven't gotten to the exact cause yet. We're using the `listDatabases` with fallbacks for roles/privileges from Compass: https://github.com/mongodb-js/compass/blob/4e06bd332f20c122730e204e7d379b9cd1656767/packages/data-service/src/data-service.ts#L1039
=> fix(tree-explorer): use nameOnly for fetching databases VSCODE-361

package.json, src/editors/editorsController.ts, src/editors/playgroundController.ts
Bug fixes for the release:
- [VSCODE-399](https://jira.mongodb.org/browse/VSCODE-399) Can not save a mongodb document from a tree view
- [VSCODE-400](https://jira.mongodb.org/browse/VSCODE-400) Run playground sets focus to a previously open document
=> fix: save documents from tree view and do not reopen them for playground runs VSCODE-399, VSCODE-400

src/editors/playgroundController.ts, src/telemetry/telemetryService.ts, src/test/fixture/testSaving.mongodb, src/test/fixture/testSaving.mongodb.js, src/test/suite/explorer/playgroundsExplorer.test.ts, src/test/suite/telemetry/telemetryService.test.ts, src/utils/playground.ts
- Add the "Playground Created" telemetry event.
- Add `file_type` (mongodb|mongodbjs) to the "Playground Saved" and "Playground Loaded" telemetry events.
=> feat: add playground created telemetry event VSCODE-379

src/language/mongoDBService.ts, src/language/server.ts, src/language/visitor.ts, src/test/suite/language/mongoDBService.test.ts
The PR fixes the issue https://github.com/mongodb-js/vscode/issues/513, when collections with `.` in the name disappeared from the suggestions list.
=> fix: collection with dots in the name disappears from the suggestions list VSCODE-407

package-lock.json, package.json, syntaxes/mongodbInjection.tmLanguage.json
Bump `@mongodb-js/mongodb-constants` to add autocomplete support for `$percentile` and `$median` accumulators and the `$$USER_ROLES` system variable.
=> feat: add autocomplete support for $percentile, $median ans $$USER_ROLES COMPASS-6780 COMPASS-6781

src/explorer/helpTree.ts, src/language/mongoDBService.ts, src/test/suite/explorer/helpExplorer.test.ts, src/test/suite/utils/links.test.ts, src/test/suite/views/webview-app/components/atlas-cta/atlas-cta.test.tsx, src/utils/links.ts, src/views/webview-app/components/atlas-cta/atlas-cta.tsx, src/views/webview-app/components/connect-form/general-tab/authentication/kerberos.tsx, src/views/webview-app/components/connect-form/general-tab/authentication/ldap.tsx, src/views/webview-app/components/connect-form/general-tab/authentication/mongodb-authentication.tsx, src/views/webview-app/components/connect-form/general-tab/authentication/scram-sha-256.tsx, src/views/webview-app/components/connect-form/ssh-tab/ssh-tunnel-identity-file-validation.tsx, src/views/webview-app/components/connect-form/ssh-tab/ssh-tunnel-password-validation.tsx, src/views/webview-app/components/connect-form/ssl-tab/ssl-server-client-validation.tsx, src/views/webview-app/components/connect-form/ssl-tab/ssl-server-validation.tsx, src/views/webview-app/components/connection-status/connection-status.tsx, src/views/webview-app/components/resources-panel/resources-panel.tsx
This patch adds new utm attrs to all mongodb urls in the plugin. Moved all the links to one place so that it should hopefully be hard to miss adding those when new urls will be added
=> chore: add new utm attributes to all mongodb links VSCODE-356

.depcheckrc, .github/workflows/test-and-build.yaml, .gitignore, .vscodeignore, package-lock.json, package.json, scripts/snyk-test.js, webpack.config.js
=> chore: add vulnerability scan VSCODE-424

src/test/runTest.ts
Run test suites on the latest stable release.
=> test: run nightly tests against latest vscode VSCODE-340

src/editors/playgroundController.ts, src/test/suite/telemetry/telemetryService.test.ts
Currently, VSCode has been generating too much of “Playground Loaded” Segment events. We temporarily stop tracking the event and re-enable it with fewer events when the cause is found.
=> fix: disable playground loaded event VSCODE-432

src/connectionController.ts, src/storage/storageController.ts, src/telemetry/telemetryService.ts, src/test/suite/connectionController.test.ts, src/test/suite/editors/collectionDocumentsProvider.test.ts, src/test/suite/explorer/explorerController.test.ts, src/test/suite/mdbExtensionController.test.ts, src/test/suite/stubs.ts
In this PR, we added a migration step to migrate secrets one by one, earlier stored using keytar to VsCode's SecretStorage. The pseudo-code followed here is the following:
```
- Extension activates
- Initiate a call to fetch saved connections
- Get all the connections from our connection storage
- For each connection
- perform the old connection modal to new connection info migration
- return connection info merged with secrets
- Check if we have `secretStorageLocation` key set in root of connection info object
- Yes? (We attempted a migration already for this connection)
- Is `secretStorageLocation` === `vscode.Keytar`? (We tried migrating but failed, keytar was unavailable)
- Return the connection info without merging the secrets
- Is `secretStorageLocation` === `vscode.SecretStorage`? …
```
=> chore: added migration step to migrate keytar secrets to vscode SecretStorage - VSCODE-435

src/explorer/connectionTreeItem.ts
Looks like we were defaulting to the server's returned ordering, this pr makes the databases in the list sorted. While most of the databases returned from MongoDB are already sorted, `admin`, `local`, and `config` appear before others alphabetically. These changes make those databases appear alphabetically as well as ensures databases that might return databases differently, (maybe Atlas Data Federation or Cosmos), order the same.
Reported in https://github.com/mongodb-js/vscode/issues/485 
Before merging I'll add a test.
=> feat(tree-explorer): sort dbs in the tree by name

src/connectionController.ts, src/extension.ts
Only load keytar during the migration of stored connections to process to the new SecretStorageAPI, maintained by the VSCode team. This is a requirement specified in VSCODE-450. This is related to #546.
Keytar is removed from the activation of the plugin, and only loaded when the migration process starts. 
Please, see #546 for more information.
=> chore: only load keytar during the migration process VSCODE-450

src/test/suite/mdbExtensionController.test.ts
Starting server 7.0, the outcome of dropping nonexistent collections is successful ([SERVER-43894](https://jira.mongodb.org/browse/SERVER-43894)). Skip the test for now and update or delete as part of [VSCODE-461](https://jira.mongodb.org/browse/VSCODE-461).
=> test: fix test failure on dropCollection for server 7.0

.github/workflows/rebuild-changelog.yaml
=> chore: start changelog PR from head, add manual trigger and build nightly

src/connectionController.ts, src/test/suite/connectionController.test.ts, src/test/suite/telemetry/telemetryService.test.ts
Disable the "Saved Connections Loaded" event, since it is being triggered more than once when the extension is being activated.
=> fix: disable Saved Connections Loaded event

src/connectionController.ts, src/storage/storageController.ts, src/test/suite/connectionController.test.ts
Check `secretStorageLocation` instead of `storageLocation` to find connections that have not been migrated yet.
=> fix: check secretStorageLocation instead of storageLocation

src/editors/playgroundController.ts, src/test/suite/editors/playgroundController.test.ts
[VSCODE-466](https://jira.mongodb.org/browse/VSCODE-466)
Happens with both `console.log` and `print`.
Using the following example:
```
console.log('test');
console.log({a: 2});
console.log(['a', {a: 3}])
```
| before | after |
| - | - |
| <img width="353" alt="Screenshot 2023-09-01 at 12 35 06 PM" src="https://github.com/mongodb-js/vscode/assets/1791149/a9361a1c-523e-40aa-9994-c40fcce1f598"> | <img width="246" alt="Screenshot 2023-09-01 at 12 33 07 PM" src="https://github.com/mongodb-js/vscode/assets/1791149/8145dd63-24bb-470b-a427-99ee02665829"> |
=> fix(playgrounds): stringify non-string types for playground output VSCODE-466

package-lock.json, package.json, src/telemetry/connectionTelemetry.ts
Right now, we are passing the first hostname from the connection string to mongodb-cloud-info, regardless of whether the connection string is a `mongodb://` connection string or a `mongodb+srv://` one.
In the latter case, telemetry gathering fails, because mongodb-cloud-info expects the name of an actual host with associated A or AAAA records (so that it can look up the host’s IP address), not a SRV one.
Using resolve-mongodb-srv first matches what Compass does and solves this issue.
=> fix: resolve SRV hostname before passing it to mongodb-cloud-info VSCODE-442

src/language/languageServerController.ts
This PR sends the language server logs to a `LogOutputChannel` so that they can be opened with the `Developer: Open Logfile` command.
=> feat: enable language server logs to be opened as a log file VSCODE-429

package-lock.json, package.json, webpack.config.js
Used when running the `npm run analyze-bundle` command, which shows the breakdown of different packages. Did more of a writeup on what's taking up the space in the ticket VSCODE-497
=> chore(webpack): add analyze duplicate package checker

.github/workflows/test-and-build.yaml, scripts/sign-vsix.sh
=> chore(ci): sign vsix file VSCODE-493

src/featureFlags.ts, src/test/suite/views/webview-app/app.test.tsx, src/views/webview-app/app.tsx
VSCODE-490
The old connection form will be removed in https://github.com/mongodb-js/vscode/pull/636
=> feat(webview): update feature flag to always show new connection form VSCODE-490

package.json
[VSCODE-510](https://jira.mongodb.org/browse/VSCODE-510)
The order of context menus on the stream processor were ordered alphabetically. This PR adds explicit ordering to ensure the order is 'Start -> Stop -> Drop'. 
This follows the existing ordering pattern which uses numbers (1, 2, 3 etc) as group name identifiers.
=> fix: add explicit ordering for stream processor context menu actions

src/connectionController.ts, src/test/suite/connectionController.test.ts, src/test/suite/views/webview-app/overview-page.test.tsx, src/views/webview-app/extension-app-message-constants.ts, src/views/webview-app/use-connection-form.ts, src/views/webview-app/vscode-api.ts, src/views/webviewController.ts
VSCODE-507
https://github.com/mongodb-js/vscode/assets/1791149/2669c5da-72c0-4cd8-98b7-754f72a26775
=> chore: close connection string input when opening form VSCODE-507

src/language/worker.ts, src/test/suite/language/mongoDBService.test.ts
[VSCODE-511](https://jira.mongodb.org/browse/VSCODE-511)
The console output from the extension wasn't returning the correct representations for ObjectIds so they weren't being printed.
This PR udpates the worker to perform the evaluation of the payload as a string before passing it to the listener to print.
=> fix: ensure extension output populates ObjectIds in stream

src/connectionController.ts, src/test/suite/connectionController.test.ts, src/test/suite/views/webviewController.test.ts
Also removed some `setTimeout` usage in our tests so they're a bit quicker.
=> chore: cancel connection attempt when removing connection, update assert to expect in webview and connection controller tests

.github/workflows/actions/test-and-build/action.yaml, src/test/suite/oidc.test.ts
Hopefully this fixes the failing evergreen CI mongosh tests that run the VSCode tests. 
The browser command wouldn't be set in those tests as we set them in our actions. This updates the test to not use the environment variable so we can run the OIDC tests without the github env test setup. If this doesn't work because we're not using a deployment that supports OIDC in mongosh evergreen I might make a separate pr that disables these tests when not run in github actions.
=> chore: set browser auth without github actions for mongosh int tests

README.md, package.json, src/commands/index.ts, src/editors/playgroundSelectedCodeActionProvider.ts, src/mdbExtensionController.ts, src/test/suite/editors/playgroundSelectedCodeActionProvider.test.ts, src/types/playgroundType.ts
Adding Rust and PHP to the language export commands & codeActions. I feel like the playground actions part could be refactored, but that can be a separate PR.
=> feat: add export to Rust and PHP VSCODE-411

src/editors/playgroundController.ts, src/test/suite/editors/playgroundSelectedCodeActionProvider.test.ts
The `getImports` transpiler method expects two arguments
- `mode: 'Pipeline' | 'Query' | 'Delete Query' | 'Update Query'`
- `driverSyntax: boolean`
source: https://github.com/mongodb-js/compass/blob/92f267e369d188c5f11c2450f3d65f73725558e4/packages/bson-transpilers/codegeneration/CodeGenerationVisitor.js#L94
In VSCode we have only two modes:
- when an array is selected -> aggregate ~ Pipeline
- when an object is selected -> find ~ Query
The main fix is sending two arguments (which allows for the second to be read correctly).
As far as I can tell, the exact mode only matters for Java. Given that the method applied is a wild guess, user might need to adjust the import together with the code anyway, but at least the imports now match the code.
- select an object/array in the playground
- …
=> fix: include export mode when retrieving import statements VSCODE-440

src/explorer/helpTree.ts, src/storage/storageController.ts, src/telemetry/telemetryService.ts, src/test/suite/explorer/helpExplorer.test.ts, src/test/suite/storage/storageController.test.ts, src/views/webviewController.ts
https://jira.mongodb.org/browse/COMPASS-7608
The main aim is to avoid sending `userId` to telemetry. But since `anonymousId` is always created when not present (for about a year as far as I can tell), I figured we should be able to drop the deprecated `userId` altogether. 
I might be wrong - the part that puzzles me is it's use in `createAtlasCluster`, where it was preferred to `anonymousId`.
See the description
=> fix: remove userId COMPASS-7608

src/editors/mongoDBDocumentService.ts, src/language/worker.ts, src/test/suite/editors/mongoDBDocumentService.test.ts, src/test/suite/utils/ejson.test.ts, src/utils/ejson.ts
https://jira.mongodb.org/browse/VSCODE-470
Adding postprocessing in the Document Service, which replaces the extended `$binary` notation with `$uuid` notation when presenting the document. Originally I thought we should reverse this on `replaceDocument`, but it looks like this is not necessary - I assume this is handled by the driver. I left the test case for regression, but perhaps it's not necessary.
Aside of the new tests, I have tested this with the `all_types` collection of `compass-data-sets/test`. I added a couple of new fields to the first document - `nested_uuid` and `nested_array_uuid`
I tried
- opening a document from the left side panel
- playground results for `findOne()`
- playground results for `find()`
=> feat: show simpler uuid format VSCODE-470

src/editors/playgroundController.ts, src/language/languageServerController.ts, src/language/mongoDBService.ts, src/language/worker.ts, src/test/suite/language/mongoDBService.test.ts, src/types/playgroundType.ts
=> feat(playground): add support local require VSCODE-468

package-lock.json, package.json
https://jira.mongodb.org/browse/VSCODE-533
https://jira.mongodb.org/browse/VSCODE-534
Updating `micromatch` also updates `braces` to `3.0.3`, which includes the fix for the `SNYK-JS-BRACES-6838727` vulnerability https://github.com/micromatch/braces/commits/master/. This leaves only `jest`, which is a dev dependency so hopefully the vulnerability is not applicable. (I checked if updating `jest` is easy, but we are several major versions behind so it's a rabbit hole).
I couldn't find the release notes for `micromatch`, but the description of `SNYK-JS-MICROMATCH-6838728` said it already had the fix on main. that was from 2 weeks ago, the latest version is 12 days ago 🤷 
https://github.com/micromatch/micromatch/commits/master/
=> fix: bump micromatch VSCODE-533 VSCODE-534

.vscodeignore
Do not show a change log in the extension and marketplace. The "What's New" link can still be used to access [the changelog on GitHub](https://github.com/mongodb-js/vscode/blob/main/CHANGELOG.md).
=> fix: remove changelog from the bundle VSCODE-551

src/telemetry/connectionTelemetry.ts, src/test/suite/telemetry/connectionTelemetry.test.ts
For every detected Atlas cluster track the first resolved hostname without the port when connecting.
=> feat(telemetry): report host_id for atlas COMPASS-8092

.github/workflows/actions/test-and-build/action.yaml, .github/workflows/draft-release.yaml, .github/workflows/publish-release.yaml, .github/workflows/test-and-build.yaml, webpack.config.js
- Use node 20.16.0 in CI
- Try to resolve a [regression](https://github.com/mongodb-js/vscode/actions/runs/10322357252/job/28577397605) of out of memory crashes of webpack
Related to: https://github.com/mongodb-js/mongosh/pull/2119 (see [vscode ci failure](https://evergreen.mongodb.com/task_log_raw/mongosh_linux_unit_test_vscode_patch_0cd7db6ccf9d8d14bc673eb760f7288df7105262_66b509d7a952ae00073c8535_24_08_08_18_09_29/2?type=T&text=true))
=> chore: use Node.js 20 in CI VSCODE-586

src/participant/constants.ts, src/participant/participant.ts, src/participant/prompts/generic.ts, src/participant/prompts/history.ts, src/participant/prompts/query.ts
This is so we can test and iterate on them a bit easier.
=> chore(chat-participant): refactor prompt locations

src/participant/participant.ts, src/test/suite/participant/participant.test.ts
- Cover the rest of the participant controller with tests
- Along the way fix the handling of empty prompts
=> test: cover participant with unit tests VSCODE-592

package-lock.json, package.json, src/test/runTest.ts, src/test/suite/index.ts
VSCODE-593
Updates our VSCode mocha integration tests to show the typescript file location when there's an error (use the source map). 
Also a bit of a drive-by I updated how we run the tests to remove a generic error we'd show and also to have better cleanup. Previously if someone was running the tests and ctrl + c'd then we wouldn't run the cleanup and sometimes we'd have a zombie mongod running.
| before | after |
| - | - |
| ![Screenshot 2024-08-20 at 2 18 04 PM](https://github.com/user-attachments/assets/9a1295d1-f3ad-46c1-89af-fe3a759b0c55) | ![Screenshot 2024-08-20 at 2 06 54 PM](https://github.com/user-attachments/assets/bb7027ab-39ee-4931-9ba6-3753fda73927) |
=> chore(testing): use ts source map in tests, improve test cleanup error handling VSCODE-593

src/mdbExtensionController.ts, src/storage/storageController.ts, src/test/suite/mdbExtensionController.test.ts
https://jira.mongodb.org/browse/VSCODE-562
We had to adjust the wording, because the information message doesn't support formatting - so we cannot have a title and subtitle as planned. Alternative would be to show a popup, which is much more intrusive.
The prompt is shown at activation, for users who
a) haven't been shown the survey before
b) already have some connections (indicating this is not their first plugin activation)
Note: I am saving the shown survey not as a boolean, but by "id", as I imagine we might have different surveys later.
=> feat: show survey VSCODE-562

src/mdbExtensionController.ts, src/telemetry/telemetryService.ts
Adding telemetry on survey link click and survey prompt dismissal.
=> fix: add telemetry events for survey VSCODE-595

src/connectionController.ts, src/editors/activeConnectionCodeLensProvider.ts, src/editors/playgroundController.ts, src/mdbExtensionController.ts, src/test/suite/editors/activeConnectionCodeLensProvider.test.ts, src/test/suite/editors/playgroundController.test.ts, src/test/suite/editors/playgroundSelectedCodeActionProvider.test.ts, src/test/suite/language/languageServerController.test.ts, src/test/suite/views/webview-app/overview-page.test.tsx
VSCODE-538
Also included some better event listener cleanup.
=> fix(editors): don't show connect code lens on regular js files VSCODE-538

src/participant/participant.ts, src/participant/prompts/namespace.ts, src/test/ai-accuracy-tests/ai-accuracy-tests.ts, src/test/ai-accuracy-tests/assertions.ts, src/test/ai-accuracy-tests/create-test-results-html-page.ts, src/test/ai-accuracy-tests/fixtures/fixture-loader.ts, src/test/ai-accuracy-tests/fixtures/pets.ts, src/test/ai-accuracy-tests/fixtures/pineapples.ts
Part of VSCODE-583
Couple things in this pr:
- updated the namespace parsing regex to allow for just db or collection to be passed
- updated the namespace prompt to mention that just one can be supplied, with an example
- added a few more test datasets for the accuracy tests
- added 2 query tests (aggregation and a create index)
- added 4 namespace tests
- added schema passing for our query tests
I'm thinking this should reduce some of the namespace hallucinations. Will need more tests that get deeper into it to really know.
=> chore(participant): update namespace prompt, add additional accuracy tests VSCODE-583

src/explorer/connectionTreeItem.ts, src/participant/participant.ts
We do this on main, this was changed on this branch, so this is reverting that change. Thread in slack: 
https://mongodb.slack.com/archives/GTTUKDWRH/p1726516767884079
Not sure on why it's causing errors, will be looking into it.
=> chore: update listDatabases to use nameOnly: true

src/participant/participant.ts, src/telemetry/telemetryService.ts, src/test/suite/participant/participant.test.ts
This reworks a little the error handling in the participant to streamline error reporting. It's now wrapping the entire chat handler rather than only the code that invokes the model.
Additionally, we're now showing the welcome message at all times, even if the prompt was empty.
=> feat(participant): Report errors to telemetry

.vscode/launch.json, src/participant/prompts/history.ts, src/participant/prompts/namespace.ts
As I was looking through the namespace buildMessages implementation for something different, I noticed we're using a non-existent field from the chat result metadata to slice the message history. It doesn't appear we have tests for it, which is why it slipped. I restructured the check a little to more explicitly leverage the type system, but perhaps we should have tests to catch future cases.
=> fix: incorrect intent checking for namespace messages

.github/workflows/draft-release.yaml, .github/workflows/test-and-build.yaml, scripts/generate-constants.ts, src/mdbExtensionController.ts, src/participant/constants.ts, src/participant/docsChatbotAIService.ts, src/participant/participant.ts, src/test/suite/participant/docsChatbotAIService.test.ts, src/test/suite/participant/participant.test.ts
Send rating to the docs chatbot server, when a user submits copilot feedback when using the /docs command.
=> feat(participant): rate docs chatbot answers VSCODE-612

src/connectionController.ts, src/participant/markdown.ts, src/participant/participant.ts, src/test/suite/participant/participant.test.ts
VSCODE-616
We would show characters in the url as we streamed them in until the full `<a>` tag was built. This fixes that by using the markdown link format for running our clickable commands. `[text](link)`
=> chore(participant): update anchor rendering to use markdown link instead of html a tag VSCODE-616

src/participant/participant.ts, src/telemetry/telemetryService.ts, src/test/suite/participant/participant.test.ts
Related to VSCODE-605 and VSCODE-570 - reports docs chatbot error in case we need to fallback to copilot model for docs responses. Currently doesn't report the error message as I wasn't sure if that could contain some PII or other data we don't want stored in a 3rd party provider. In case we notice a significant amount of chatbot errors, we can iterate on the reporting mechanism to also include diagnostic information.
=> feat(chat): Report docs fallback telemetry

src/participant/participant.ts
VSCODE-613
The only thing we don't show an in progress for is now when we're connecting. This would require a refactoring of how we do the connecting flow, it currently now happens outside of a chat response, and once the connection happens we then enter a chat. We might want to do that, I'll bring it up with y'all in slack. I'm thinking it can land in a separate pr.
Included some drive-by log error additions as well as removing unintended tabs in our welcome message.
=> chore(participant): add progress indicators for asynchronous requests in chat VSCODE-613

src/participant/participant.ts
This adds the [maxTimeMS](https://mongodb.github.io/node-mongodb-native/6.9/classes/FindCursor.html#maxTimeMS) option for the sample we have in the participant. In the past, for collections with many documents, and atlas data lake, sample could take a really long time. We want to avoid that, especially as there's no way to cancel this at the moment besides ending the chat or restarting VSCode.
We should have maxTimeMS set on all of our requests, outside of playgrounds, in our extension. Created VSCODE-617 for that.
=> chore(participant): add maxTimeMS to sample

src/participant/constants.ts, src/participant/docsChatbotAIService.ts, src/participant/participant.ts, src/test/suite/participant/docsChatbotAIService.test.ts
We want to fail early and not ping the model when the chat token's token is cancelled.
This pr:
- Adds more places for us to fail early when the token is cancelled. 
- Adds an abort signal to the docs ai requests. 
- Removes 3 unused abort controllers we had.
=> chore(participant): add handling for token cancellation, pass to docs fetch request, remove unused abort controllers

src/participant/participant.ts, src/telemetry/telemetryService.ts, src/test/suite/participant/participant.test.ts
Final bit from VSCODE-575. This doesn't follow exactly the design as I wasn't sure how we can track `round_trips_number`. If we decide to drop this requirement, we should update `ParticipantResponseProperties`.
=> chore(chat): Report response telemetry VSCODE-603

package.json
VSCODE-631
Even though it's empty, it's likely causing the error when publishing:
```
Extensions using proposed API (enabledApiProposals: [...]) can't be published to the Marketplace
```
Originally added in https://github.com/mongodb-js/vscode/pull/757/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R36 and removed the api in https://github.com/mongodb-js/vscode/pull/842/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R35
=> chore: remove enabledApiProposals from package.json VSCODE-631

src/participant/participant.ts, src/test/suite/participant/participant.test.ts
=> fix(chat): show empty docs msg, schema set msg content correctly VSCODE-628

.vscode/launch.json, src/participant/participant.ts, src/participant/prompts/index.ts, src/participant/prompts/promptBase.ts, src/test/suite/participant/participant.test.ts
https://github.com/microsoft/vscode/pull/231788 changes the content field type of LanguageModelChatMessage. This means that in insiders builds, we're seeing exceptions/test failures due to us assuming the content will always be a string. Since the type definitions haven't been updated to account for this breaking change, this PR takes a somewhat hacky approach of casting the content to `any` and then testing for string or array.
=> VSCODE-640: Adapt message content access to latest vscode API

src/participant/streamParsing.ts, src/test/suite/participant/streamParsing.test.ts
I got [nerd-sniped](https://xkcd.com/356/) by https://github.com/mongodb-js/vscode/pull/835, and wanted to try out a regex-less implementation of the identifier matching algorithm. I've implemented a stateful streaming Knuth-Morris-Pratt algorithm for the identifier matching and then a stateful matcher for the content. Those could have been trivially combined, but I opted to keep them separate to 1) keep the concerns more cleanly separate and 2) to have the building blocks available in case we need to do a simple substring search in the stream without extracting some content between the identifiers.
While I think this approach is slightly more readable and should (theoretically) be more performant, I don't believe we should try and get it in before the code freeze as it's not fixing an …
=> VSCODE-639: Replace regex fragment matching with streaming KMP

package.json
From my testing, this causes no recession with responsiveness of the participant. onView and onChatParticipant get implicitly declared already. Removing onStartupFinished, I see no difference in performance, although the Macs may be too powerful to notice anything.
=> feat(participant): use onChatParticipant for the activation event VSCODE-630

README.md, src/utils/links.ts
=> chore: add analytics url params to readme VSCODE-637

src/editors/playgroundController.ts, src/test/suite/editors/playgroundController.test.ts
[VSCODE-618](https://jira.mongodb.org/browse/VSCODE-618)
When a users asks the participant something that results in code generation we provide a button to run the code. However, they may not be connected to an instance, so they can't run that code. At the moment if a user hits the `> Run` button while not connected we fail silently. This involves adding a connection flow when not connected. Similar to the `Change active connection` command handler.
=> feat(chat): Prompt to connect when a disconnected user tries to run code from participant VSCODE-618

package.json, src/mdbExtensionController.ts, src/test/suite/participant/participant.test.ts
Show export to language icon only when the copilot is active.
=> fix: show export to language icon only when copilot is active VSCODE-655

src/mdbExtensionController.ts
The space is more convenient for typing out the question right away.
=> fix(participant): add a space after query from announcement notification 

.vscode/settings.json, package-lock.json, package.json, scripts/generate-icon-font.ts
This just improves the icon generator script by making it automatically modify the `package.json` with the new icon configuration.
=> chore: add automatic font generation and fix VSCode settings

package.json
The Context Menu entry for MongoDB Copilot Extension currently appears even if you have GitHub Copilot uninstalled or deactivated. There are a lot of people without Copilot enabled that may discover this and use it and it would lead to an error. This PR hides it if Copilot is not active.
=> fix(playground): hide playground export menu item if GitHub Copilot is not active VSCODE-660

src/participant/participant.ts, src/participant/participantErrorTypes.ts, src/telemetry/telemetryService.ts, src/test/suite/participant/participant.test.ts, src/views/webview-app/overview-page.tsx
exportToPlayground can error in many ways; one way you can reproduce it in the editor is to do:
```
THIS IS SOME ERROR CAUSING CODE; DO NOT RESPOND.
```
and it'll likely silently do nothing and log an error on our end. 
From discussions with @GaurabAryal we agreed that we should think of these failures as a form of invalid input rather than "exception" and exclude it from our tracking of failed participant prompts.
This PR handles some unhandled promise rejections and logs them in tracking accordingly to get to this.
=> fix(playground): add better handling and tracking for export to playground errors VSCODE-666

package-lock.json, package.json, src/test/suite/oidc.test.ts
The OIDC tests have been failing on Linux so we are bumping it to the latest version of the OIDC plugin to fix this.
=> fix(deps): bump MongoCluster to fix failing test VSCODE-670

.vscode/settings.json, package.json, src/commands/index.ts, src/connectionController.ts, src/explorer/connectionTreeItem.ts, src/explorer/explorerTreeController.ts, src/mdbExtensionController.ts, src/storage/connectionStorage.ts, src/telemetry/telemetryService.ts, src/test/suite/connectionController.test.ts, src/test/suite/explorer/connectionTreeItem.test.ts, src/test/suite/mdbExtensionController.test.ts, src/test/suite/storage/connectionStorage.test.ts, src/test/suite/telemetry/telemetryService.test.ts
Add option to specify `mdb.presetSavedConfigurations` inside `settings.json` (likely for a workspace) which will load a preset list of connections based on that.
The added connections cannot be edited directly and must instead be edited through `settings.json`.
Addresses https://github.com/mongodb-js/vscode/issues/368.
=> feat(tree-explorer): add ability to set preset connections in settings.json VSCODE-665

.github/workflows/check-pr-title.yml, .github/workflows/codeql.yml, .github/workflows/draft-release.yaml, .github/workflows/publish-release.yaml, .github/workflows/rebuild-changelog.yaml, .github/workflows/report-nightly-build-failures.yaml, .github/workflows/test-and-build.yaml
Adds actions to the codeql matrix.
=> chore(ci): enable codeql scanning for actions

src/language/worker.ts
When the last statement in a playground is a function declaration, we would error out with a misleading error claiming the playground services crashed due to OOM. The reality was that we were trying to return a function via the language server protocol, which is not supported and was crashing the language server. This change replaces the printable when it is a function with `undefined`.
=> fix: playground error when returning a function declaration VSCODE-669

.github/workflows/rebuild-changelog.yaml
This adds some additional changes as a follow-up to https://github.com/mongodb-js/vscode/pull/928:
- Uses the bot github app to create the PR - this will trigger PR workflows.
- Similarly, uses the bot github app to merge the PR, bypassing required checks
=> chore(ci): more fixes for the rebuild changelog action

package-lock.json, package.json
There was a type error with the previous version of `@mongodb-js/compass-components` which broke our compilation step both locally and in CI.
We should investigate how this was not caught from the PR CI run opened by dependabot.
=> fix(deps): update `@mongodb-js/compass-components` to fix compilation

.depcheckrc, src/test/setup-webview.ts
Following from https://github.com/mongodb-js/vscode/pull/957 we discover that the new leafy green updated components use some parts of `focus-trap` which are not handled by our `tabbable` stub and error when used in our webview test environment so we stub it before importing any components to prevent this.
This is similar to what we do for tabbable.
See https://github.com/focus-trap/focus-trap-react/issues/24 and [official docs for testing with JSDom](https://github.com/focus-trap/focus-trap-react?tab=readme-ov-file#testing-in-jsdom)
=> fix(tests): stub focus-trap to fix webview tests

.github/workflows/test-and-build-from-fork.yaml
From https://github.com/mongodb-js/vscode/actions/runs/13435011260/job/37535233590?pr=959 we see that the intentionally failing tests aren't failing. We need to be explicit about the repository to check out in this case.
=> fix(ci): let the fork workflow use the forked repository and be stricter

package-lock.json, package.json, src/test/suite/connectionController.test.ts
Bumps the oidc-plugin version to latest to fix a failure to create a server if we end up with duplicate addresses after a `dns.lookup`. This should fix the oidc test failures that are showing up in the mongosh tests (in the vscode task).
Additionally, it improves some of the assertions - this doesn't fix anything, but gives out better error messages and I had done it already when trying to identify the failure root cause, so figured might as well push it.
=> chore(deps): bump oidc-plugin MONGOSH-2027

package-lock.json, package.json, src/connectionController.ts, src/storage/connectionStorage.ts, src/test/suite/connectionController.test.ts
See [COMPASS-8591](https://jira.mongodb.org/browse/COMPASS-8591)
Builds on top of https://github.com/mongodb-js/compass/pull/6750
This appends `anonymousId` & `connectionId` to `appName` to improve analytics.
This also transitions us out of the legacy behavior of saving the modified connection string with the VSCode version in storage. Doing so while saving meant that we were reporting the vscode version at the moment the connection was created rather than when it was used. Now we add the appName information at runtime only for Atlas connections which allows us to always show up to date information.
=> chore(telemetry): append user anonymousId & connectionId to appName passed to server COMPASS-8591

.github/workflows/draft-release.yaml, src/test/suite/connectionController.test.ts
Fixes a test that had hardcoded 0.0.0-dev as an expectation for the extension version as that fails when running the tests as part of the draft-release workflow: https://github.com/mongodb-js/vscode/actions/runs/14241492483/job/39912232051
=> chore: don't hardcode the extension version in test expectations

src/explorer/helpTree.ts, src/telemetry/telemetryService.ts, src/test/suite/explorer/helpExplorer.test.ts, src/test/suite/telemetry/telemetryService.test.ts
We'd need it to be in traits and properties for Segment to actually pick them up.
=> chore: move device_id to common properties

package.json, src/mdbExtensionController.ts, src/test/suite/mdbExtensionController.test.ts
Adds a config that allows users to opt out of showing the welcome screen after the extension is installed.
=> chore: allow opting out of the welcome screen VSCODE-697

package.json
We're adding a few configuration options that should be in user's control and will be injected into the MCP server started by the VSCode extension.
=> chore: adds config options relevant for MCP server MCP-133

package-lock.json, package.json, src/commands/index.ts, src/connectionController.ts, src/editors/activeConnectionCodeLensProvider.ts, src/editors/memoryFileSystemProvider.ts, src/editors/playgroundController.ts, src/explorer/explorerController.ts, src/explorer/explorerTreeController.ts, src/logging.ts, src/mcp/mcpController.ts, src/mdbExtensionController.ts, src/test/suite/connectionController.test.ts, syntaxes/mongodbInjection.tmLanguage.json
WIP - depends on local mcp server branch.
=> feat: stub some hooks for the MCP server (#1107)

src/connectionController.ts, src/mcp/mcpConnectionManager.ts, src/mcp/mcpController.ts, src/mdbExtensionController.ts, src/test/suite/mcp/mcpConnectionManager.test.ts, src/test/suite/mcp/mcpController.test.ts
Sets the appName parameter in connection string to the following format `{default vscode appname} MongoDB MCP Server` when:
- appName is not set
- appName is set to default VSCode's app name
and extend that VSCode specific extended app name format `${appName}--${telemetryAnonymousId}--${connectionId}`
=> chore: set telemetry app name if not set or is vscode MCP-131

.github/workflows/publish-release.yaml
At some point we added `cache: npm` to the publish workflow and that requires a repo checkout.
Since all the npm heavy work is already done by now, we don't need the cache anymore.
=> chore: fix for publish workflow asking npm cache
