mongodb-js/vscode

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/PULL_REQUEST_TEMPLATE.md
.vscode/settings.json
README.md
azure-pipelines.yml
package-lock.json
package.json
src/test/runTest.ts
src/test/suite/index.ts

- Add basic azure pipelines configuration
- Add PR templates
- Update dependencies

VSCODE-13: Continuous integration

---

azure-pipelines.yml
src/explorer/index.ts
tsconfig.json

Currently, we don't have many dependencies, therefore it is hard to tell how beneficial it is to have cache :) I separated `npm cache`, `npm install` and `test running` into separate steps to be able to measure running time in the future.
**Without cache:**
**With cache:**

VSCODE-13: enable caching

---

LICENSE
package.json

chore: Apache 2.0 license

---

src/syntaxes/mongodb.tmLanguage.json

Fetch an updated mongodb grammar with grouped keywords.

VSCODE-39: fetch updated mongodb grammar

---

azure-pipelines.yml
package-lock.json
package.json

Ubuntu 18.04 instead of Ubuntu 16.04 made flakey "not visible" error you had in #17 VSCODE-36.
Flakey test bad... Needed to go away and just happened into a fix. Other BUILD related cleanup while I'm at it.

ci(azure): Use latest Ubuntu (18.04) to fix flakey test on Linux Azure job

---

package.json
src/mdbExtensionController.ts
src/test/suite/extension.test.ts

Add a command to create a new MongoDB playground.

VSCODE-45 create playground

---

.vscode/launch.json
src/explorer/databaseTreeItem.ts
src/templates/playgroundTemplate.ts
src/test/runTest.ts
src/test/suite/explorer/databaseTreeItem.test.ts
src/test/suite/stubs.ts

Sorts collections in alphanumerical order.
I expect collections to be in alphanumerical order, otherwise I have to scan them all to find the one I need.
- Not sure why they don't come back already in the right order.

Sort collections in tree-view

---

package-lock.json
src/templates/playgroundTemplate.ts

- Add the `db.sales.drop()` command to a playground template to allow users to run a template script more than once. Since running a script adds data to a collection and all the next runs documents with the same keys can not be inserted and causes the duplicate key error.
- Add a comment to the beginning of the template that reminds users to be connected before running a playground. Only connected users can run a playground or benefit from the completion feature.
- Add a comment that tells users how to use the completion feature inside snippets and string literals.

VSCODE-101: Update a playground template

---

README.md

Slight edits, minor changes to telemetry language.

Minor Edits

---

package-lock.json
package.json

Bumps connection model and data service to get the updates for ssh tunneling.

Bump mongodb-connection-model package to 16.0.1

---

README.md
package.json

* mentioned known issue with launching shell on Windows in README
* fixed description for shell selector dropdown in settings

Pre-launch copy tweaks

---

package.json

We had one `and` too many in the description.
It can go live with the next release.

Removed an extra `and` from the description copy

---

README.md

Add documentation on how to run a playground.

Add instruction for actually running a playground.

---

CHANGELOG.md
package-lock.json
package.json

First updates to the `changelog.md` following https://keepachangelog.com/en/1.0.0/

Bump to version 0.0.3

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/question.md

Use unique names for bug report and question templates to enable them on GitHub.

Fix: use unique names for templates

---

src/language/mongoDBService.ts
src/mdbExtensionController.ts
src/test/suite/extension.test.ts
src/test/suite/views/webviewController.test.ts
src/views/webview-app/components/connect-form/ssl/ssl-server-client-validation.tsx
src/views/webview-app/connection-model/connection-model.ts
src/views/webview-app/store/actions.ts
src/views/webview-app/store/store.ts
src/views/webviewController.ts

VSCODE-125: Connect with SSL to mongodb shell

---

src/language/mongoDBService.ts

https://jira.mongodb.org/browse/VSCODE-121
The node `worker_threads` package had a change in v12.5.0 that returned a promise instead of running synchronously: https://nodejs.org/api/worker_threads.html#worker_threads_worker_terminate
It appears remote WSL (Windows subsystem for Linux) is using the older version of worker threads, while vanilla vscode isn't. https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl I'm going to dig a bit deeper and see if there's a PR we can do so that the worker threads/node version gets bumped up, this fix should cover our use case though.
This PR changes how we terminate the worker to allow it to return possibly synchronously using `await`. No test changes, if we find more errors from WSL maybe it's worth making a testing …

VSCODE-121: Remote WSL playground fix

---

src/editors/playgroundController.ts
src/telemetry/telemetryController.ts

- Extend the "Playground Code Executed" event with 2 additional properties:
- partial = `true|false`: to record if it's been a partial execution
- error = `true|false`: to record if there has been an error. This is especially important to understand if users tend to select portions of code that can't run. If this happens a lot, we might need to help them a bit more in the future.
- Move code lens under selection to cover cases when a long piece of code was selected

VSCODE-153: track partial execution and errors

---

CHANGELOG.md
package-lock.json
package.json

Changelog changes:
- Added the ability to run partial playgrounds
- Added indexes to the explorer tree view
- Fixed an issue with the launch shell command in powershell
- Fixed an issue with the tree explorer freezing when double clicking an open schema

Update changelog, bump version to 0.1.0

---

package-lock.json
package.json
snippets/stage-autocompleter.json

pulls in https://github.com/mongodb-js/ace-autocompleter/pull/57

Bump ace autocompleter to 0.4.11 with search snippet update

---

src/connectionController.ts

Improves the connect with uri experience. Somehow totally missed this option when building it xD
https://code.visualstudio.com/api/references/vscode-api#InputBoxOptions

Update connection uri input to not hide on focus out

---

src/views/webview-app/components/connect-helper/connect-helper.less
src/views/webview-app/components/connection-status/connection-status.less
src/views/webview-app/components/info-sprinkle/info-sprinkle.less

This PR adds hovers to the buttons on the overview page

Improve overview page button state styles

---

package-lock.json
package.json
snippets/stage-autocompleter.json

This pulls in PR: https://github.com/mongodb-js/ace-autocompleter/pull/65

fix(COMPASS-4492): remove sql pipeline stage operator

---

package.json
src/test/suite/explorer/helpExplorer.test.ts
src/test/suite/views/webview-app/components/atlas-cta/atlas-cta.test.tsx
src/test/suite/views/webviewController.test.ts
src/views/webview-app/components/atlas-cta/atlas-cta.tsx
src/views/webview-app/extension-app-message-constants.ts
src/views/webview-app/store/actions.ts
src/views/webview-app/store/store.ts
src/views/webviewController.ts

VSCODE-211
This PR improves how we open the free cluster link from the overview page.

feat(VSCODE-211): Open atlas create cluster link from webview

---

src/templates/playgroundTemplate.ts

"Make sure you run it against proper database and collection." -> "Make sure you run it against the correct database and collection."

Grammar fix on the VS Code Playground template

---

src/explorer/helpTree.ts
src/test/suite/explorer/helpExplorer.test.ts
src/test/suite/views/webview-app/components/atlas-cta/atlas-cta.test.tsx
src/views/webview-app/components/atlas-cta/atlas-cta.tsx

With this new link for Atlas registration page we take users to a more contextual, VS Code-related experience.

New link for Atlas registration page

---

azure-pipelines.yml
package-lock.json
package.json
src/commands/launchMongoShell.ts
src/test/suite/commands/launchMongoShell.test.ts

Use a proper command format to launch shell in bash for ssl.

VSCODE-227: Use a proper command format to launch shell in bash for ssl

---

package-lock.json

chore: bump mongodb-download-url to 1.0.0

---

src/language/server.ts

fix: remove placeholder validation from language server VSCODE-246

---

README.md
package.json
src/test/suite/commands/launchMongoShell.test.ts

As we approach the GA of the new MongoDB Shell (`mongosh`), let's make it the default.

Make `mongosh` the default shell

---

package-lock.json
package.json

For dependebot: https://github.com/mongodb-js/vscode/pull/319

deps: bump yargs-parser to latest - 20.2.9

---

CONTRIBUTING.md

VSCODE-279
Once this is merged I'll update our internal docs to link to this.
Here's how it looks:
The MongoDB VSCode extension is not released on a set schedule. A new version is released on demand or when there are some features ready to go live.
Releases are automated using github actions, and published to the VSCode marketplace using a Personal Access Token (PAT).
1. To kick off a release run `npm run release-draft *.*.*|major|minor|patch` on the main branch. This will run the [release draft script](https://github.com/mongodb-js/vscode/blob/main/scripts/release-draft.js) which creates a new tag for the release.
1. When that tag has been created, the GitHub action for building the extension is automatically started: https://github.com/mongodb-js/vscode/blob/main/.github/workflows/test-a …

chore(docs): Add release documentation VSCODE-279

---

.github/workflows/publish-release.yaml

ci: uncomment release step ✨ 

---

.github/workflows/publish-release.yaml

fix(ci): add PAT to publish command

---

.github/workflows/test-and-build.yaml

fix(ci): remove newline at end of changelog line VSCODE-282

---

README.md

Not sure if this is all that helpful to have, maybe we should remove it all together? Do y'all find them useful in projects?
Here's how it looks: [![Build Status](https://github.com/mongodb-js/vscode/actions/workflows/test-and-build.yaml/badge.svg?branchName=update-badge-in-readme)](https://github.com/mongodb-js/vscode/actions/workflows/test-and-build.yaml)

fix: add github actions badge, remove azure pipelines badge

---

package-lock.json
package.json
src/test/suite/telemetry/telemetryService.test.ts

chore: remove deprecated classnames package types

---

.github/workflows/test-and-build.yaml

Node-gyp continues throwing installation errors. It is some kind of versions conflict. Made tests succeed for `node@14.17.3` when previously didn't work for `node@^14.17.3` that was installing `node@14.8.1`.

build: try to install windows-build-tools

---

src/connectionController.ts
src/explorer/explorerTreeController.ts
src/test/suite/connectionController.test.ts
src/test/suite/dbTestHelper.ts
src/test/suite/explorer/databaseTreeItem.test.ts
src/test/suite/explorer/fieldTreeItem.test.ts
src/test/suite/explorer/schemaTreeItem.test.ts
src/test/suite/telemetry/connectionTelemetry.test.ts
src/views/webview-app/connection-model/constants/auth-strategies.ts
src/views/webview-app/connection-model/legacy-connection-model.ts

Write more tests to ensure a proper connection format is passed across the app and check data stored to the disc.

test: add tests cases for connection info and secrets VSCODE-317

---

.github/workflows/node-gyp-workaround.sh
.github/workflows/publish-release.yaml
.github/workflows/test-and-build.yaml

fix(ci): add node-gyp workaround script

---

package-lock.json
package.json

chore: bump ace autocompleter to 0.11.0 COMPASS-5556

---

CONTRIBUTING.md

chore(docs): changes the product name in Contributing.md

---

src/language/mongoDBService.ts
src/test/suite/language/mongoDBService.test.ts

Add links to MQL documentation.
Since we going to refactor [mongodb-constants](https://github.com/mongodb-js/devtools-shared/tree/main/packages/mongodb-constants) suggestion templates, we could use [VSCODE-394](https://jira.mongodb.org/browse/VSCODE-394) to also add documentation and examples to query and aggregation operators.

feat: add links to MQL documentation VSCODE-387

---

src/templates/playgroundCreateIndexTemplate.ts

The columnstore indexes support is not expected for the current version, so we remove it because we think that would lead to less confusion later.

refactor: remove columnstore indexes COMPASS-6783

---

.github/workflows/test-and-build.yaml

chore(ci): fix  create-jira-tickets task

---

package-lock.json
package.json

chore(ci): truncate origins for vulnerability reports in jira

---

.prettierignore
.snyk

This PR is built on top of #556, only meant to ignore the snyk vulnerability since the advisory hasn't been updated yet.

chore: ignore semver vuln since snyk advisory has not been updated yet with the new backported patches

---

.github/workflows/rebuild-changelog.yaml

chore: update rebuild-changelog.yaml to add base branch

---

package-lock.json
package.json

fix(deps): bump to mongodb driver 5.8.1 VSCODE-464

---

.snyk

chore: ignore axios vuln reported by snyk as it doesn't affect our product VSCODE-476

---

package.json
src/test/suite/commands/launchMongoShell.test.ts
src/test/suite/connectionController.test.ts
src/test/suite/dbTestHelper.ts
src/test/suite/editors/playgroundSelectedCodeActionProvider.test.ts
src/test/suite/explorer/explorerController.test.ts
src/test/suite/language/mongoDBService.test.ts
src/test/suite/mdbExtensionController.test.ts
src/test/suite/playground.test.ts
src/test/suite/storage/storageController.test.ts
src/test/suite/telemetry/connectionTelemetry.test.ts
src/test/suite/views/webviewController.test.ts

chore: update mongodb-runner testing server port

---

src/logging.ts

Sending logs to a `LogOutputChannel` instead of a regular `OutputChannel` enables vscode to pick up our logfile in the `Developer: Open Logfile` action.  
Here's a demo that opens the logfile using the `Developer: Open Logfile` command:
https://github.com/mongodb-js/vscode/assets/23407842/02cb0ff0-18ad-4404-a499-5e4ace13a70e

feat: send logs to a LogOutputChannel VSCODE-429

---

.depcheckrc
.prettierrc.json
package-lock.json
package.json

chore: use shared devtools prettier config instead of compass one

---

package-lock.json

chore(deps): bump socks to 2.7.3 VSCODE-520

---

package.json

feat: add changeActiveConnection command to palette

---

package-lock.json

chore(deps): update jose

---

package-lock.json
package.json
src/telemetry/connectionTelemetry.ts
src/test/suite/telemetry/connectionTelemetry.test.ts

Do not resolve srv twice. Use resolved srv from topology.

refactor(telemetry): use resolved srv from topology VSCODE-563

---

src/editors/playgroundController.ts
src/mdbExtensionController.ts
src/participant/participant.ts
src/test/suite/editors/playgroundController.test.ts
src/test/suite/editors/playgroundSelectedCodeActionProvider.test.ts
src/test/suite/language/languageServerController.test.ts
src/test/suite/participant/participant.test.ts

Cover the /query command with unit tests. More tests will follow in separate PRs.

test: setup participant unit tests VSCODE-592

---

src/connectionController.ts
src/editors/activeConnectionCodeLensProvider.ts
src/editors/playgroundController.ts
src/mdbExtensionController.ts
src/storage/storageController.ts
src/telemetry/telemetryService.ts
src/test/suite/editors/activeConnectionCodeLensProvider.test.ts
src/test/suite/editors/playgroundController.test.ts
src/test/suite/editors/playgroundSelectedCodeActionProvider.test.ts
src/test/suite/language/languageServerController.test.ts
src/test/suite/mdbExtensionController.test.ts
src/test/suite/views/webview-app/overview-page.test.tsx

Sync the feature branch with the main.

chore: sync with main 26 08

---

src/participant/participant.ts
src/participant/prompts/query.ts
src/participant/schema.ts
src/test/suite/participant/participant.test.ts

Include schema when sending requests to the copilot's model.

feat: send schema to the model for better results VSCODE-581

---

webpack.config.js

fix: clean-up webpack config VSCODE-597

---

webpack.config.js

Use empty import for `electron` and `hadron-ipc` instead of import as externals.

fix: cannot find module electron VSCODE-598

---

src/test/ai-accuracy-tests/ai-accuracy-tests.ts
src/test/ai-accuracy-tests/assertions.ts
src/test/ai-accuracy-tests/fixtures/fixture-loader.ts
src/test/ai-accuracy-tests/fixtures/fixture-type.ts
src/test/ai-accuracy-tests/fixtures/recipes.ts
src/test/ai-accuracy-tests/fixtures/ufo.ts

chore(participant): add test, refactor test fixture loading structure

---

src/test/ai-accuracy-tests/ai-accuracy-tests.ts
src/test/ai-accuracy-tests/assertions.ts
src/test/ai-accuracy-tests/create-test-results-html-page.ts
src/test/ai-accuracy-tests/fixtures/antiques.ts
src/test/ai-accuracy-tests/fixtures/fixture-loader.ts
src/test/ai-accuracy-tests/test-setup.ts

chore(participant): add sample docs test and debug prompts var VSCODE-583

---

src/participant/participant.ts
src/telemetry/telemetryService.ts
src/test/suite/participant/participant.test.ts

Part of VSCODE-575 - adds tracking for the welcome prompt. The refactoring of the tests is not absolutely necessary, but I noticed we have a lot of code duplication and some inconsistencies, which bugged me a bit, so went ahead and did it as a drive-by. If people have strong opinions, I can split it into a different PR.

feat(participant): Report telemetry for welcome VSCODE-602

---

package.json
src/participant/prompts/query.ts
src/test/ai-accuracy-tests/ai-accuracy-tests.ts
src/test/suite/participant/participant.test.ts

VSCODE-528
Updates to the prompt:
- Moved the namespace, schema, and sample document passing to the user prompt. I think these should be in the user prompt as we don't want any of the information from the data to impact what the ai will respond with. This is similar to a system prompt, if you allow for unsanitized text to make it's way into the system prompt then it can be susceptible to things like prompt injection.
- Removed "You can imagine the schema."
- Changed around some of the language to be a bit more intentional (hopefully? this is hard to measure the impact of).
- Updated the examples to have the ```javascript wrapper around the code.
The accuracy tests are very limited in what they're testing, so take them with a grain of salt, they don't indicate much except that the prompt …
```

chore(participant): update query prompt, update accuracy test config to include proposed api types

---

package.json

From https://code.visualstudio.com/api/extension-guides/chat#publishing-your-extension
> Update the attributes in the package.json to make it easy for users to find your extension. Add "AI" and "Chat" to the categories field in your package.json.
https://code.visualstudio.com/api/references/extension-manifest
I also added "Data Science" since I thought it was fitting, we can remove it if folks think it's better without.

chore: add chat and ai categories to package.json VSCODE-627

---

src/participant/participant.ts

chore(participant): move docs references after content VSCODE-629

---

package-lock.json
package.json
src/connectionController.ts
src/test/suite/explorer/explorerController.test.ts
src/views/webview-app/connection-form.tsx
src/views/webview-app/overview-page.tsx

Update to the new Connection Form.
It should work the same, minor changes are the subtitle and horizontal line above the button.

fix: use new connection form

---

package-lock.json

Bumps devtools-connect and by extension devtools-proxy-support to latest.

chore: update devtools-connect to latest VSCODE-649

---

src/participant/prompts/exportToPlayground.ts

Use `<>` for a collection placeholder for a consistent formatting.
Follow up to: https://github.com/mongodb-js/vscode/pull/887#pullrequestreview-2477036635

fix(copilot): wrap collection name placeholder in angle brackets VSCODE-654

---

.github/workflows/test-and-build-from-fork.yaml

Moves merging to a separate job to avoid races between the different matrix components.

chore(ci): fix dependabot workflow

---

.github/workflows/rebuild-changelog.yaml

Changes the rebuild changelog action to list all releases. Additionally, it should now correctly skip unpublished releases.

chore: fix rebuild-changelog action

---

src/connectionController.ts
src/test/suite/connectionController.test.ts

It is actually possible to end up "removing" a preset connection when using the command palette...
It does "remove" the connection for the session and doesn't error but this removal doesn't persist on refresh (since the preset connection just gets reloaded from the config). 
This changes it so we instead filter that.

fix: hide preset connections from the Remove Connection command VSCODE-674

---

src/mcp/mcpController.ts

fix: add hosting_mode to mcp telemetry
